#!/usr/bin/env python3
"""
FROZEN evaluator for fsx_B_0906 -- "Raw-Material Order Book: Hitting a Product Mix
Through Batch Yields" (family: production-mix-ordering; format B, quality-metric;
theme: order raw materials to hit a product mix).

THEME.  A small plant can buy K=3 products' worth of raw material from P raw-material
TYPES.  Raw type j is processed in whole BATCHES of lot[j] raw units: every complete
batch of j yields the fixed output vector yield[j] (K nonnegative integers, "batch
yield" -- both the raw purchase AND the batch conversion are governed by this fixed
process).  Raw units bought beyond the last complete batch are WASTED (no output, but
still paid for).  You choose an integer purchase quantity order[j] >= 0 (bounded by
maxOrder[j]) for every raw type; the number of complete batches actually run is
nb[j] = order[j] // lot[j].

MECHANISM 1 -- integrality-gap.  Because output only appears in whole-batch lumps, the
reachable output vectors form an integer lattice generated by the yield[] vectors, not
a continuous cone: a continuous (fractional-batch) plan that looks perfect on paper can
be far off once every raw type's purchase is rounded down to whole lots, especially
when lot sizes are large relative to the batch counts actually affordable.

MECHANISM 2 -- lp-inversion.  Naively "inverting" the yield matrix per PRODUCT --
picking, for each product independently, whichever single raw type is the cheapest
source of that product and buying it in proportion to the product's target share --
ignores that most raw types are MIXED recipes that also produce the other products as
a side effect.  Summing several independently-chosen per-product allocations therefore
double-counts side yields and drifts the realized ratio far from the target.

MECHANISM 3 -- yield-uncertainty.  Every raw type has a FULL-YIELD batch allowance
thresh[j]: only the first thresh[j] batches of a purchase run at full yield[j]; every
batch beyond that is degraded (scaled by the fraction degrade_num[j]/degrade_den[j],
rounded down per product) because the process was only tuned for a limited run length.
A plan that dumps a large purchase onto one "cheap-looking" raw type without checking
its threshold gets much less real output than the sticker yield promised, wasting
money and skewing the ratio.

INNOVATION HOOK (what `strong` exploits).  The set of ratios a NON-negative combination
of the P raw types can realize is well approximated by the CONVEX HULL, on the product
simplex, of the raw types' own normalized FULL-yield directions norm(yield[j])
(scaling a single raw type up or down leaves its ratio at or very near dir(yield[j]) --
exactly there as long as every batch runs full-rate, and only nudged by small integer
per-product flooring once batches beyond thresh[j] degrade; combining two raw types
traces close to the segment between their two directions). Some target ratios lie far
enough outside that hull that no purchase, however combined, can ever reach them --
the right move is to project the target onto the nearest point of the reachable hull
(the nearest edge between two raw types' directions, or a single raw type's own
direction) instead of chasing the unreachable point at ballooning cost. Once the right
target RATIO is identified, the plan must also respect batch integrality and the
full-yield threshold (mechanisms 1 and 3) when converting that ratio into actual
integer purchase quantities -- both because whole-lot rounding matters and because the
hull itself is only a first-order (undegraded-yield) approximation of what is truly
reachable, so the final batch counts must be checked against the REAL simulated output.

CANDIDATE CONTRACT (isolated stdin -> stdout program).
  stdin : ONE JSON object (the PUBLIC instance):
    {"P": int, "K": 3,
     "lot":   [lot_0 ... lot_{P-1}],                 # positive ints, batch size
     "yield": [[yield_j_0, yield_j_1, yield_j_2] for j in range(P)],   # nonneg ints, sum>0
     "cost":  [cost_0 ... cost_{P-1}],                # positive ints, cost per raw UNIT bought
     "thresh": [thresh_0 ... thresh_{P-1}],           # positive ints, full-yield batch allowance
     "degrade_num": [...], "degrade_den": [...],      # 0 < num < den, per-batch decay beyond thresh
     "maxOrder": [maxOrder_0 ... maxOrder_{P-1}],      # positive ints, purchase upper bound per type
     "target": [t_0, t_1, t_2]}                        # target product ratio, sums to 1
  stdout: ONE JSON object:
    {"order": [order_0, ..., order_{P-1}]}             # integer purchase quantity per raw type

  VALID iff "order" is a list of exactly P integers (or integer-valued numbers), each
  order[j] in [0, maxOrder[j]].  Any violation (wrong length/type, out-of-range,
  NaN/inf, bool, crash, timeout, non-JSON) -> 0.0 on that instance.

TRANSITION (deterministic).  For raw type j: nb = order[j] // lot[j]; spend +=
order[j]*cost[j] (ALL bought units are paid for, including the leftover below one
batch -- that leftover is pure waste). For each complete batch b = 1..nb: if
b <= thresh[j], add yield[j] to the running output vector; else add
floor(yield[j][k] * degrade_num[j] / degrade_den[j]) per product k.

SCORING (deterministic; no wall-time). Let output = the resulting K-vector and
ratio = output / sum(output) (or, if sum(output) == 0, a maximally-wrong ratio i.e.
deviation forced to 2.0 -- ordering nothing can never match a target).  Per instance:
    dev  = sum_k |ratio[k] - target[k]|             # in [0, 2]
    obj  = dev + GAMMA * (spend / spend_cap)         # spend_cap = sum(maxOrder[j]*cost[j])
The evaluator ALSO computes its own weak baseline() construction (buy exactly one
batch of the single cheapest-per-unit raw type, ignoring the target entirely) and its
objective b.  Final per-instance ratio: r = min(1, 0.1 * b / max(obj, eps)); the score
is the mean of r over 10 fixed seeded instances.  Lower obj is better (this is a
MINIMIZATION objective internally, mapped increasingly into r).

ISOLATION. The candidate is untrusted and runs in a FRESH bwrap-SANDBOXED SUBPROCESS
via `isorun.run_candidate`; it only ever sees the PUBLIC instance above.

CLI: python3 evaluator.py <solution.py>
"""
import sys, json
import isorun

K = 3
GAMMA = 0.5


# ----------------------------- deterministic RNG ---------------------------
def _rng(seed):
    state = (seed * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)

    def nxt_int(lo, hi):
        nonlocal state
        state = (state * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)
        return lo + (state >> 17) % (hi - lo + 1)

    return nxt_int


def _norm(v):
    s = sum(v)
    if s <= 0:
        return [0.0] * len(v)
    return [x / s for x in v]


def _mk_pure(nxt, k, big_lo=8, big_hi=11, other_lo=2, other_hi=4):
    """Dominant single-product recipe; capped so its own ratio share stays <= ~0.75
    (never a full 100% source of any product -- keeps some targets provably
    unreachable without any recipe looking absurdly extreme)."""
    y = [0, 0, 0]
    y[k] = nxt(big_lo, big_hi)
    for kk in range(3):
        if kk != k:
            y[kk] = nxt(other_lo, other_hi)
    return y


def _mk_mixed(nxt, k1, k2, lo=3, hi=9, other_hi=2):
    y = [0, 0, 0]
    y[k1] = nxt(lo, hi)
    y[k2] = nxt(lo, hi)
    other = [kk for kk in range(3) if kk not in (k1, k2)][0]
    y[other] = nxt(0, other_hi)
    return y


def _finish_recipe(nxt, y, cost_lo=5, cost_hi=13, lot_lo=3, lot_hi=8,
                    thresh_lo=2, thresh_hi=4, cap_lo=6, cap_hi=10,
                    cost=None, thresh=None, degrade=None):
    lot = nxt(lot_lo, lot_hi)
    c = cost if cost is not None else nxt(cost_lo, cost_hi)
    th = thresh if thresh is not None else nxt(thresh_lo, thresh_hi)
    if degrade is not None:
        dn, dd = degrade
    else:
        choices = [(1, 2), (2, 3), (1, 3), (3, 4)]
        dn, dd = choices[nxt(0, len(choices) - 1)]
    cap = nxt(cap_lo, cap_hi)
    maxOrder = lot * cap
    return {"yield": y, "lot": lot, "cost": c, "thresh": th,
            "degrade_num": dn, "degrade_den": dd, "maxOrder": maxOrder}


def _pack(name, recipes, target):
    P = len(recipes)
    inst = {
        "name": name, "P": P, "K": K,
        "lot": [r["lot"] for r in recipes],
        "yield": [r["yield"] for r in recipes],
        "cost": [r["cost"] for r in recipes],
        "thresh": [r["thresh"] for r in recipes],
        "degrade_num": [r["degrade_num"] for r in recipes],
        "degrade_den": [r["degrade_den"] for r in recipes],
        "maxOrder": [r["maxOrder"] for r in recipes],
        "target": target,
    }
    inst["spend_cap"] = sum(inst["maxOrder"][j] * inst["cost"][j] for j in range(P))
    return inst


# ----------------------------- instance builders ----------------------------
def _build_reachable_pair(seed):
    """Sanity topology: target is an exact convex combination of TWO of the five raw
    types' own directions, so it is exactly reachable via a two-material mix -- but the
    recipes are still mixed enough that naive per-product single-sourcing (mechanism 2)
    does not automatically find that mix."""
    nxt = _rng(seed)
    recipes = [
        _finish_recipe(nxt, _mk_pure(nxt, 0)),
        _finish_recipe(nxt, _mk_mixed(nxt, 1, 2)),
        _finish_recipe(nxt, _mk_pure(nxt, 1)),
        _finish_recipe(nxt, _mk_mixed(nxt, 0, 2)),
        _finish_recipe(nxt, _mk_pure(nxt, 2)),
    ]
    i, j = 0, 1
    while j == i:
        j = nxt(0, len(recipes) - 1)
    i = nxt(0, len(recipes) - 1)
    j = (i + 1 + nxt(0, len(recipes) - 2)) % len(recipes)
    t = nxt(30, 70) / 100.0
    di = _norm(recipes[i]["yield"])
    dj = _norm(recipes[j]["yield"])
    target = [round(t * di[k] + (1 - t) * dj[k], 6) for k in range(3)]
    s = sum(target)
    target = [x / s for x in target]
    return _pack(f"reachable{seed}", recipes, target)


def _build_unreachable_corner(seed, dom=0.85):
    """Trap topology (cone / lp-inversion): target puts `dom` weight on one product,
    while every recipe's OWN share of that product is capped well below `dom` -- by
    the convex-hull argument no non-negative purchase combination can ever reach it.
    Greedy's naive per-product inversion keeps throwing more of the best single source
    at the shortfall, over-purchasing (and, on top of it, tripping that source's
    yield-degradation threshold) instead of recognizing the ratio is unattainable and
    settling on the nearest reachable point."""
    nxt = _rng(seed)
    kstar = nxt(0, 2)
    recipes = []
    # recipe 0: the "obvious" (cheap, best per-unit) but capped-share source for kstar
    y0 = _mk_pure(nxt, kstar, big_lo=9, big_hi=11, other_lo=2, other_hi=4)
    recipes.append(_finish_recipe(nxt, y0, cost=nxt(4, 6), thresh=nxt(1, 2), degrade=(1, 2)))
    others = [kk for kk in range(3) if kk != kstar]
    recipes.append(_finish_recipe(nxt, _mk_mixed(nxt, others[0], others[1])))
    recipes.append(_finish_recipe(nxt, _mk_pure(nxt, others[0])))
    recipes.append(_finish_recipe(nxt, _mk_pure(nxt, others[1])))
    recipes.append(_finish_recipe(nxt, _mk_mixed(nxt, kstar, others[0])))
    target = [0.0, 0.0, 0.0]
    target[kstar] = dom
    rem = 1.0 - dom
    target[others[0]] = round(rem * 0.6, 6)
    target[others[1]] = round(1.0 - target[kstar] - target[others[0]], 6)
    return _pack(f"unreach{seed}", recipes, target)


def _build_degrade_trap(seed):
    """Trap topology (yield-uncertainty): the cheapest, highest-yield source for the
    dominant target product has a LOW full-yield threshold (thresh=1) and halves after
    that. A high target share for that product tempts a scale-proportional purchase
    plan into many batches of the cheap source, most of them degraded -- realized
    output falls well short and spend is wasted on the discount that never materializes.
    A second, pricier but non-degrading source can supply the rest efficiently."""
    nxt = _rng(seed)
    kstar = nxt(0, 2)
    others = [kk for kk in range(3) if kk != kstar]
    y_cheap = _mk_pure(nxt, kstar, big_lo=9, big_hi=11, other_lo=1, other_hi=3)
    cheap = _finish_recipe(nxt, y_cheap, cost=nxt(3, 5), lot_lo=3, lot_hi=4,
                            thresh=1, degrade=(1, 2), cap_lo=8, cap_hi=10)
    y_steady = _mk_pure(nxt, kstar, big_lo=6, big_hi=8, other_lo=1, other_hi=2)
    steady = _finish_recipe(nxt, y_steady, cost=nxt(9, 12), thresh=nxt(5, 6), degrade=(3, 4))
    recipes = [cheap, steady,
               _finish_recipe(nxt, _mk_mixed(nxt, others[0], others[1])),
               _finish_recipe(nxt, _mk_pure(nxt, others[0])),
               _finish_recipe(nxt, _mk_pure(nxt, others[1]))]
    target = [0.0, 0.0, 0.0]
    target[kstar] = 0.6
    target[others[0]] = round(nxt(15, 25) / 100.0, 6)
    target[others[1]] = round(1.0 - target[kstar] - target[others[0]], 6)
    return _pack(f"degrade{seed}", recipes, target)


def _build_interleaved_mixed(seed, P=5):
    """Trap topology (lp-inversion): NO recipe is a clean single-product source -- every
    raw type is a mixed recipe covering two products with a small side yield of the
    third. Picking a per-product 'best single source' independently and summing those
    allocations double-counts side yields across the overlapping recipes, dragging the
    realized ratio far from target; only an explicit combined (pairwise convex) search
    over the actual recipes finds an accurate mix."""
    nxt = _rng(seed)
    pairs = [(0, 1), (1, 2), (0, 2), (0, 1), (1, 2)]
    recipes = []
    for idx in range(P):
        k1, k2 = pairs[idx % len(pairs)]
        recipes.append(_finish_recipe(nxt, _mk_mixed(nxt, k1, k2, lo=3, hi=9, other_hi=2)))
    i = nxt(0, P - 1)
    j = (i + 1 + nxt(0, P - 2)) % P
    t = nxt(25, 75) / 100.0
    di = _norm(recipes[i]["yield"])
    dj = _norm(recipes[j]["yield"])
    target = [t * di[k] + (1 - t) * dj[k] for k in range(3)]
    s = sum(target)
    target = [round(x / s, 6) for x in target]
    return _pack(f"interleave{seed}", recipes, target)


def _build_holdout(seed, P=6):
    """Held-out generalization topology: larger P, a randomized blend of pure/mixed
    recipes, a randomized threshold/degrade profile on several raw types, and a target
    that may land inside OR outside the reachable hull depending on the seed -- a
    broader stress test combining all three mechanisms at once."""
    nxt = _rng(seed)
    recipes = []
    for idx in range(P):
        roll = nxt(0, 2)
        if roll == 0:
            y = _mk_pure(nxt, nxt(0, 2))
        else:
            k1 = nxt(0, 2)
            k2 = (k1 + 1 + nxt(0, 1)) % 3
            y = _mk_mixed(nxt, k1, k2)
        th = nxt(1, 3) if nxt(0, 3) == 0 else nxt(4, 6)
        dg = (1, 2) if th <= 2 else (3, 4)
        recipes.append(_finish_recipe(nxt, y, thresh=th, degrade=dg))
    kstar = nxt(0, 2)
    others = [kk for kk in range(3) if kk != kstar]
    dom = nxt(55, 80) / 100.0
    target = [0.0, 0.0, 0.0]
    target[kstar] = dom
    target[others[0]] = round((1 - dom) * (nxt(30, 70) / 100.0), 6)
    target[others[1]] = round(1.0 - target[kstar] - target[others[0]], 6)
    return _pack(f"holdout{seed}", recipes, target)


def _build_instances():
    out = []
    out.append(_build_reachable_pair(101))
    out.append(_build_reachable_pair(102))
    out.append(_build_unreachable_corner(201, dom=0.85))
    out.append(_build_unreachable_corner(202, dom=0.88))
    out.append(_build_degrade_trap(301))
    out.append(_build_degrade_trap(302))
    out.append(_build_interleaved_mixed(401))
    out.append(_build_interleaved_mixed(402))
    out.append(_build_holdout(501, P=6))
    out.append(_build_holdout(502, P=6))
    return out


# ----------------------------- transition / scoring -------------------------
def simulate(inst, order):
    P = inst["P"]
    output = [0, 0, 0]
    spend = 0.0
    for j in range(P):
        oj = order[j]
        lot = inst["lot"][j]
        nb = oj // lot
        spend += oj * inst["cost"][j]
        th = inst["thresh"][j]
        dn = inst["degrade_num"][j]
        dd = inst["degrade_den"][j]
        y = inst["yield"][j]
        full_b = min(nb, th)
        for k in range(3):
            output[k] += full_b * y[k]
        degraded_b = max(0, nb - th)
        if degraded_b > 0:
            for k in range(3):
                output[k] += degraded_b * ((y[k] * dn) // dd)
    return output, spend


def objective(inst, order):
    output, spend = simulate(inst, order)
    tot = sum(output)
    if tot <= 0:
        dev = 2.0
    else:
        ratio = [x / tot for x in output]
        dev = sum(abs(ratio[k] - inst["target"][k]) for k in range(3))
    obj = dev + GAMMA * (spend / inst["spend_cap"])
    return obj


def baseline(inst):
    P = inst["P"]
    j_cheap = min(range(P), key=lambda j: (inst["cost"][j], j))
    order = [0] * P
    order[j_cheap] = inst["lot"][j_cheap]
    return objective(inst, order)


# ----------------------------- validation ------------------------------------
def _valid_order(inst, answer):
    if not isinstance(answer, dict):
        return None
    order = answer.get("order")
    if not isinstance(order, list) or len(order) != inst["P"]:
        return None
    out = []
    for j, v in enumerate(order):
        if isinstance(v, bool):
            return None
        if isinstance(v, int):
            iv = v
        elif isinstance(v, float):
            if v != v or v in (float("inf"), float("-inf")) or v != int(v):
                return None
            iv = int(v)
        else:
            return None
        if not (0 <= iv <= inst["maxOrder"][j]):
            return None
        out.append(iv)
    return out


def score(inst, answer):
    order = _valid_order(inst, answer)
    if order is None:
        return False, None
    obj = objective(inst, order)
    if not (obj == obj) or obj in (float("inf"), float("-inf")) or obj < 0:
        return False, None
    return True, obj


# ----------------------------- scoring driver ---------------------------------
def main():
    if len(sys.argv) < 2:
        print("usage: evaluator.py <solution.py>")
        sys.exit(2)
    cand = sys.argv[1]
    instances = _build_instances()

    vec = []
    for inst in instances:
        b = baseline(inst)
        # NOTE: "name" is deliberately withheld from the public payload -- it is only
        # an internal debugging label for the fixed instance suite, and sending it
        # would let a candidate special-case on the (deterministic, always-reused)
        # instance identity instead of solving the numeric instance it is given.
        public = {"P": inst["P"], "K": inst["K"],
                  "lot": list(inst["lot"]), "yield": [list(r) for r in inst["yield"]],
                  "cost": list(inst["cost"]), "thresh": list(inst["thresh"]),
                  "degrade_num": list(inst["degrade_num"]), "degrade_den": list(inst["degrade_den"]),
                  "maxOrder": list(inst["maxOrder"]), "target": list(inst["target"])}
        ans, st = isorun.run_candidate(cand, public, timeout=20)
        if st != "OK":
            vec.append(0.0)
            continue
        try:
            ok, obj = score(inst, ans)
        except Exception:
            ok, obj = False, None
        if not ok:
            vec.append(0.0)
            continue
        r = min(1.0, 0.1 * b / max(obj, 1e-9))
        if not (r == r) or r < 0.0 or r > 1.0:
            r = 0.0
        vec.append(r)

    ratio = sum(vec) / len(vec) if vec else 0.0
    print("Ratio: %.6f" % ratio)
    print("Vector: " + json.dumps([round(x, 6) for x in vec]))


if __name__ == "__main__":
    main()
