function print_supp_vis()

string = ['\\begin{figure*}[t!]\n' ...
'\\def \\sz {0.475}\n' ...
'\\centering\n' ...
'\\includegraphics[width=\\sz\\linewidth]{figures/feature-explorer/supp/supp-x3-y3-c%d-p1.pdf}\n' ...
'\\hspace{5pt}\n' ...
'\\includegraphics[width=\\sz\\linewidth]{figures/feature-explorer/supp/supp-x3-y3-c%d-p1.pdf}\n' ...
'\\includegraphics[width=\\sz\\linewidth]{figures/feature-explorer/supp/supp-x3-y3-c%d-p1.pdf}\n' ...
'\\hspace{5pt}\n' ...
'\\includegraphics[width=\\sz\\linewidth]{figures/feature-explorer/supp/supp-x3-y3-c%d-p1.pdf}\n' ...
'\\includegraphics[width=\\sz\\linewidth]{figures/feature-explorer/supp/supp-x3-y3-c%d-p1.pdf}\n' ...
'\\hspace{5pt}\n' ...
'\\includegraphics[width=\\sz\\linewidth]{figures/feature-explorer/supp/supp-x3-y3-c%d-p1.pdf}\n' ...
'\\includegraphics[width=\\sz\\linewidth]{figures/feature-explorer/supp/supp-x3-y3-c%d-p1.pdf}\n' ...
'\\hspace{5pt}\n' ...
'\\includegraphics[width=\\sz\\linewidth]{figures/feature-explorer/supp/supp-x3-y3-c%d-p1.pdf}\n' ...
'\\includegraphics[width=\\sz\\linewidth]{figures/feature-explorer/supp/supp-x3-y3-c%d-p1.pdf}\n' ...
'\\hspace{5pt}\n' ...
'\\includegraphics[width=\\sz\\linewidth]{figures/feature-explorer/supp/supp-x3-y3-c%d-p1.pdf}\n' ...
'\\figlabel{vis%d}\n' ...
'\\end{figure*}\n\n'];

fid = fopen('supp_vis.tex', 'w');
for i = 1:2:256
   fwrite(fid, sprintf(string, i, i+1, i));
end
fclose(fid);
