#!/usr/bin/env python3
"""Instance generator for "Polyomino Tiling Coverage" (ALE-Bench heuristic optimization).

Usage:
    python3 gen.py <seed>

Writes one instance to stdout in the format:

    H W P
    (then, for each of the P piece types, on its own lines:)
    k                    -- number of cells in the polyomino
    dr_0 dc_0            -- k lines of integer cell offsets (the shape), one per line
    ...
    dr_{k-1} dc_{k-1}
    avail                -- how many copies of this piece type may be used (>= 0)

Meaning. We are given an H x W board (all cells initially empty) and P polyomino
piece TYPES. Piece type t is described by a set of k_t unit cells given as integer
(row, col) OFFSETS; the listed offsets are already normalized so that
min(dr)=0, min(dc)=0 (the shape touches the top and left of its bounding box).
A placement chooses a type t, a rotation rot in {0,1,2,3} (rot quarter-turns
clockwise), and an anchor cell (r, c); the placed cells are the rotated offsets
(re-normalized to min 0) shifted by (r, c). A placement is legal iff all its cells
lie on the board and no cell of any placed piece overlaps another. Each type t may
be used at most avail_t times. The objective is to MAXIMIZE the number of covered
(occupied) board cells. This is a packing / exact-cover-style problem; it is
NP-hard, has no closed-form optimum, and is scored by a continuous coverage count
(see score.py / context.md for the exact rule and the feasibility -> 0 floor).

Instance regime (deterministic from the seed):
  * Board H, W in the low tens (W <= 60 so a board row fits one 64-bit word, which
    is what the intended bitmask solver exploits).
  * P piece types in [4, 9], each a small polyomino of 3..6 cells generated by a
    random growth walk, then normalized; avail per type a handful.
  * The total available area (sum over types of avail_t * k_t) comfortably exceeds
    H*W, so full coverage is information-theoretically possible but combinatorially
    hard -- exactly the regime where a strong add/remove local search beats a plain
    largest-piece-first greedy that paints itself into uncoverable holes.
"""
import sys
import random


def gen_polyomino(rng, k):
    """Grow a connected polyomino of k cells by a random walk on the grid, then
    normalize so min row = min col = 0. Returns a sorted list of (dr, dc)."""
    cells = {(0, 0)}
    while len(cells) < k:
        # pick a random frontier cell and extend in a random 4-direction
        base = rng.choice(list(cells))
        dr, dc = rng.choice([(-1, 0), (1, 0), (0, -1), (0, 1)])
        cand = (base[0] + dr, base[1] + dc)
        cells.add(cand)
    rmin = min(r for r, _ in cells)
    cmin = min(c for _, c in cells)
    norm = sorted(((r - rmin, c - cmin) for (r, c) in cells))
    return norm


def main() -> None:
    if len(sys.argv) < 2:
        sys.stderr.write("usage: gen.py <seed>\n")
        sys.exit(1)
    seed = int(sys.argv[1])
    rng = random.Random(0x20A7_0000 ^ (seed * 2654435761 & 0xFFFFFFFF))

    H = rng.randint(12, 26)
    W = rng.randint(12, 26)
    P = rng.randint(4, 9)

    pieces = []          # list of (cells, avail)
    total_avail_area = 0
    for _ in range(P):
        k = rng.randint(3, 6)
        cells = gen_polyomino(rng, k)
        avail = rng.randint(2, 6)
        pieces.append((cells, avail))
        total_avail_area += avail * len(cells)

    # Make sure the available area comfortably exceeds the board area, so full
    # coverage is in principle possible (the difficulty is the packing, not a
    # shortage of pieces). Bump avails until we have >= 1.6 * H * W cells.
    need = int(1.6 * H * W)
    guard = 0
    while total_avail_area < need and guard < 10000:
        idx = rng.randrange(P)
        cells, avail = pieces[idx]
        pieces[idx] = (cells, avail + 1)
        total_avail_area += len(cells)
        guard += 1

    out = [f"{H} {W} {P}"]
    for (cells, avail) in pieces:
        out.append(str(len(cells)))
        for (dr, dc) in cells:
            out.append(f"{dr} {dc}")
        out.append(str(avail))
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
