# TIER: strong
import sys

# INSIGHT: don't fit one blended term. The data is generated by TWO additive,
# physically-named contributions that scale differently with lam:
#   a bulk/area term  ~ (a*b) * lam            (grows linearly in lam)
#   a boundary/perimeter term ~ (2*(a+b)) * sqrt(lam)   (grows like sqrt(lam))
# Because lam and sqrt(lam) are highly correlated over any single moderate
# range, a joint least-squares fit of both terms at once is ill-conditioned
# and recovers garbage coefficients. The robust move is to EXPLOIT the
# regime structure instead of fighting the collinearity:
#   Step 1: at the LARGEST lam values in the sample, the area term utterly
#           dominates (its share of the signal is > 95%), so a single-feature
#           fit restricted to those rows recovers the area coefficient C1
#           cleanly.
#   Step 2: subtract that area contribution from the SMALLEST-lam rows
#           (where the residual signal-to-noise for the boundary term is
#           best) and fit the remaining residual against
#           [perimeter*sqrt(lam), 1] to recover the boundary coefficient C2
#           and the constant term C3.
# This decomposition -- estimate each physically-named contribution in the
# regime where its signature dominates, then compose them -- is exactly
# what lets the formula extrapolate correctly to the elongated held-out
# pans, where the boundary term's share of the signal is no longer small.


def read_rows():
    data = sys.stdin.read().split()
    it = iter(data)
    k = int(next(it))
    rows = []
    for _ in range(k):
        a = float(next(it)); b = float(next(it)); lam = float(next(it)); n = float(next(it))
        rows.append((a, b, lam, n))
    return rows


def main():
    rows = read_rows()

    distinct_lams = sorted(set(r[2] for r in rows))
    m = len(distinct_lams)
    k_hi = max(1, m // 4)
    k_lo = max(1, m // 4)
    hi_set = set(distinct_lams[m - k_hi:])
    lo_set = set(distinct_lams[:k_lo])

    # ---- Step 1: area coefficient from the high-lam subset (single feature) ----
    sxy = 0.0
    sxx = 0.0
    for a, b, lam, n in rows:
        if lam in hi_set:
            x = a * b * lam
            sxy += x * n
            sxx += x * x
    C1 = sxy / sxx if sxx > 1e-12 else 0.0

    # ---- Step 2: residual regression on the low-lam subset: [P*sqrt(lam), 1] ----
    s11 = s12 = s22 = 0.0
    sy1 = sy2 = 0.0
    cnt = 0
    for a, b, lam, n in rows:
        if lam in lo_set:
            resid = n - C1 * a * b * lam
            f1 = 2.0 * (a + b) * (lam ** 0.5)
            f2 = 1.0
            s11 += f1 * f1
            s12 += f1 * f2
            s22 += f2 * f2
            sy1 += f1 * resid
            sy2 += f2 * resid
            cnt += 1

    det = s11 * s22 - s12 * s12
    if abs(det) > 1e-9 and cnt >= 2:
        c_neg = (sy1 * s22 - s12 * sy2) / det
        c3 = (s11 * sy2 - s12 * sy1) / det
    else:
        c_neg = 0.0
        c3 = 0.0
    C2 = -c_neg

    print("%.8f * a * b * lam - %.8f * ( 2 * ( a + b ) ) * ( lam ** 0.5 ) + %.8f" % (C1, C2, c3))


if __name__ == "__main__":
    main()
