#!/usr/bin/env python3
"""
FROZEN evaluator for fsx_A_0878 -- "Loading Dock Phase Shift: Calibrated Eviction"
(family: cache-phase-oracle; format B, quality-metric).

THEME.  A warehouse loading-dock cache holds C pallets on its staging shelf. A
stream of pull requests arrives for pallet IDs; a request for a pallet already on
the shelf is a HIT, otherwise it's a MISS and (if the shelf is full) some resident
pallet must be evicted to make room. The floor also runs a "runner" who radios a
noisy FORECAST at every request: their guess of how many requests until this
pallet is needed again. The runner is sometimes an expert (forecast tightly
tracks the truth) and sometimes basically guessing -- or even backwards -- and
WHICH regime is active changes without warning partway through a shift
(a phase shift in the workload's working set). Neither ignoring the runner
(plain LRU) nor blindly trusting them (Belady-on-the-forecast) wins across a
whole shift; the win is estimating the runner's CURRENT trustworthiness from
recent outcomes and re-estimating it again whenever the workload's regime
shifts.

CANDIDATE CONTRACT (isolated stdin -> stdout program), run ONCE PER INSTANCE.
  stdin : ONE JSON "public" object -- capacity, and a CALIBRATION trace (pallet
          ids + forecasts, generated by the SAME recipe as the real shift but a
          DIFFERENT draw) so the candidate can empirically measure how well the
          forecast tracked truth on data it is allowed to fully see.  The candidate
          NEVER sees the real shift's pallet sequence -- only this calibration
          sample.
  stdout: ONE JSON "policy" object describing an eviction RULE (not a raw
          decision list):
            {"mode": "lru" | "hint" | "blend",
             "init_trust": float in [0,1],     # only used for "blend"
             "decay": float in [0,1],          # EWMA step size for trust updates
             "window": int in [2,50],          # miss-rate lookback for phase-edge flags
             "edge_threshold": float in [0,1], # miss-rate that flags a regime change
             "reset_on_edge": bool}            # re-seed trust at a flagged edge
          The evaluator (trusted) then REPLAYS the real, hidden shift causally,
          one request at a time, applying this policy with an internal adaptive
          engine -- the candidate's own process never touches the real trace, so
          there is no full-lookahead shortcut available.

SCORING (deterministic; no wall-time).  For the real hidden trace we compute,
in the trusted PARENT process only:
    m_base  = misses under the internal always-LRU policy (weak baseline)
    m_opt   = misses under a true CLAIRVOYANT optimal policy (exact next-use
              lookahead over the real trace -- an unreachable ideal; a noisy,
              forecast-only, causally-replayed policy cannot generally match it)
    m_cand  = misses produced by REPLAYING the candidate's policy
  and normalize with an affine anchor (weak baseline -> 0.1, ideal -> 1.0):
    r = clamp( 0.1 + 0.9 * (m_base - m_cand) / max(1, m_base - m_opt), 0, 1 )
  Always-LRU reproduces the baseline exactly -> r == 0.1.  Blindly trusting the
  forecast scores WELL on expert-runner stretches but scores near/below 0 on the
  guessing/backwards stretches (a bad bet actively costs hits vs. LRU). Because
  m_opt uses full true lookahead a noisy forecast cannot recover, even a
  well-calibrated policy stays below 1.0 -- real headroom remains.

ISOLATION.  The candidate is untrusted and runs in a FRESH SUBPROCESS via
`isorun.run_candidate`; it only ever sees the calibration sample, never the real
trace, the true next-use gaps, or m_base/m_opt.

CLI:  python3 evaluator.py <solution.py>
Prints:
  Ratio: <mean r over all instances, in [0,1]>
  Vector: [r_1, r_2, ...]
"""
import sys, json, math
from bisect import bisect_right
from collections import deque
import isorun


# ----------------------------- deterministic RNG ---------------------------
def _rng(seed):
    state = (seed * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)

    def nxt_int(lo, hi):
        nonlocal state
        state = (state * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)
        return lo + (state >> 17) % (hi - lo + 1)

    def nxt_unit():
        nonlocal state
        state = (state * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)
        return ((state >> 11) & ((1 << 53) - 1)) / float(1 << 53)

    return nxt_int, nxt_unit


# ----------------------------- trace generation -----------------------------
# A "recipe" is a list of phase specs: (kind, length, reliability, wsize).
#   kind: "cycle" (working set of `wsize` pallets, revisited in a shuffled loop
#         each lap -- LRU-unfriendly once wsize > C) or "hot" (locality: mostly
#         reuses one of the last few pallets -- LRU-friendly).
#   reliability: "good" (forecast ~= true gap + small noise), "bad" (forecast is
#         an independent random gap, uncorrelated with truth), "adv" (forecast
#         is the truth's mirror -- actively points at the wrong pallet).

def _gen_trace(seed, recipe, n_pages, max_gap_hint):
    ni, nu = _rng(seed)
    pages = list(range(n_pages))
    trace = []
    for kind, length, rel, wsize in recipe:
        if kind == "cycle":
            wset = [pages[ni(0, n_pages - 1)] for _ in range(wsize)]
            # a lap = one shuffled pass through the working set (deterministic
            # Fisher-Yates using the seeded RNG), repeated until length reached
            pos = length
            while pos > 0:
                lap = wset[:]
                for i in range(len(lap) - 1, 0, -1):
                    j = ni(0, i)
                    lap[i], lap[j] = lap[j], lap[i]
                take = lap[:pos] if pos < len(lap) else lap
                trace.extend(take)
                pos -= len(take)
        else:  # "hot": locality-biased picks among a recent-window + fresh draws.
            # The recent-window is sized off `wsize` directly (not shrunk), so
            # when wsize > C (the trap recipes) the "hot" locality set itself
            # doesn't comfortably fit in the cache and eviction choice matters;
            # wsize=0 recipes keep a small window (an easy, low-pressure filler).
            recent = []
            rw = max(4, wsize) if wsize > 0 else 4
            for _ in range(length):
                if recent and ni(0, 99) < 85:
                    p = recent[ni(0, len(recent) - 1)]
                else:
                    p = pages[ni(0, n_pages - 1)]
                trace.append(p)
                recent.append(p)
                if len(recent) > rw:
                    recent.pop(0)
    # ---- true next-occurrence gap per position (0 = adjacent repeat, SENTINEL
    #      if never seen again in this trace) ----
    SENT = max_gap_hint
    N = len(trace)
    next_pos = {}
    true_gap = [0] * N
    for t in range(N - 1, -1, -1):
        p = trace[t]
        true_gap[t] = (next_pos[p] - t) if p in next_pos else SENT
        next_pos[p] = t
    # ---- forecast per position, driven by this position's phase reliability ----
    hints = [0] * N
    idx = 0
    for kind, length, rel, wsize in recipe:
        for _ in range(length):
            t = idx
            g = true_gap[t]
            if rel == "good":
                noise = ni(0, 4) - 2
                h = g + noise if g < SENT else SENT + ni(0, 4) - 2
            elif rel == "bad":
                h = ni(0, SENT)
            else:  # "adv": mirror the truth so large truth -> small forecast and vice versa
                gg = g if g < SENT else SENT
                h = (SENT - gg) + (ni(0, 4) - 2)
            if h < 0:
                h = 0
            hints[t] = h
            idx += 1
    return trace, hints, true_gap


def _recipe_for(kind_tag, C):
    """Deterministic recipe families; wsize scaled off capacity C."""
    W = C + max(3, C // 2)          # cycle working set > C -> genuine eviction pressure
    if kind_tag == "reliable_cycle":
        return [("cycle", 90, "good", W), ("hot", 70, "good", 0),
                ("cycle", 90, "good", W)]
    if kind_tag == "noisy_hot":                       # trap: blind hint-trust
        return [("hot", 80, "bad", W), ("hot", 90, "bad", W), ("hot", 70, "bad", W)]
    if kind_tag == "adversarial_hot":                 # trap: hint actively lies
        return [("hot", 80, "adv", W), ("hot", 90, "adv", W)]
    if kind_tag == "phase_edge_good_to_bad":           # trap: regime flips mid-shift
        return [("cycle", 110, "good", W), ("hot", 110, "bad", W)]
    if kind_tag == "phase_edge_bad_to_good":
        return [("hot", 100, "bad", W), ("cycle", 120, "good", W)]
    if kind_tag == "mixed_thirds":
        return [("cycle", 70, "good", W), ("hot", 70, "bad", W), ("cycle", 70, "good", W)]
    if kind_tag == "long_reliable_cycle":              # harder / larger held-out
        return [("cycle", 140, "good", W), ("hot", 90, "good", 0),
                ("cycle", 140, "good", W)]
    if kind_tag == "triple_flip":                      # harder / larger held-out
        return [("hot", 70, "bad", W), ("cycle", 80, "good", W),
                ("hot", 70, "adv", W), ("cycle", 90, "good", W)]
    if kind_tag == "gentle_mostly_good":
        return [("cycle", 60, "good", W), ("hot", 60, "good", 0), ("hot", 60, "bad", W)]
    if kind_tag == "hot_locality_baseline":
        return [("hot", 130, "good", 0), ("hot", 130, "good", 0)]
    raise ValueError(kind_tag)


def _build_instances():
    """10 deterministic instances: (seed, C, n_pages, kind_tag)."""
    specs = [
        (101, 8, 26, "reliable_cycle"),
        (102, 8, 26, "noisy_hot"),
        (103, 8, 26, "adversarial_hot"),
        (104, 9, 28, "phase_edge_good_to_bad"),
        (105, 9, 28, "phase_edge_bad_to_good"),
        (106, 8, 24, "mixed_thirds"),
        (107, 10, 30, "gentle_mostly_good"),
        (108, 8, 24, "hot_locality_baseline"),
        # harder / larger held-out
        (211, 12, 40, "long_reliable_cycle"),
        (212, 10, 34, "triple_flip"),
    ]
    out = []
    for seed, C, n_pages, tag in specs:
        recipe = _recipe_for(tag, C)
        # calibration shift runs the SAME recipe ~2x longer than the real shift
        # (last week's full logs) so a candidate's empirical backtest is less
        # at the mercy of one short draw's noise than the real shift itself.
        calib_recipe = [(k, l * 2, r, w) for (k, l, r, w) in recipe]
        max_gap_hint = sum(l for _, l, _, _ in calib_recipe) + 10
        real_trace, real_hints, _ = _gen_trace(seed * 2 + 1, recipe, n_pages, max_gap_hint)
        calib_trace, calib_hints, _ = _gen_trace(seed * 2 + 7919, calib_recipe, n_pages, max_gap_hint)
        out.append({
            "name": f"dock{seed}", "capacity": C, "n_pages": n_pages, "tag": tag,
            "real_trace": real_trace, "real_hints": real_hints,
            "calib_trace": calib_trace, "calib_hints": calib_hints,
        })
    return out


# ----------------------------- replay engine --------------------------------
def _clip(x, lo, hi):
    if not isinstance(x, (int, float)) or isinstance(x, bool):
        return None
    if x != x or x in (float("inf"), float("-inf")):
        return None
    return max(lo, min(hi, float(x)))


def _validate_policy(ans):
    """Strict validation. Returns a normalized policy dict, or None if invalid."""
    if not isinstance(ans, dict):
        return None
    mode = ans.get("mode")
    if mode not in ("lru", "hint", "blend"):
        return None
    pol = {"mode": mode}
    if mode == "blend":
        it = _clip(ans.get("init_trust", 0.5), 0.0, 1.0)
        dc = _clip(ans.get("decay", 0.1), 0.0, 1.0)
        wd = ans.get("window", 10)
        eth = _clip(ans.get("edge_threshold", 0.5), 0.0, 1.0)
        roe = ans.get("reset_on_edge", False)
        if it is None or dc is None or eth is None:
            return None
        if isinstance(wd, bool) or not isinstance(wd, int) or not (2 <= wd <= 50):
            return None
        if not isinstance(roe, bool):
            return None
        pol.update(init_trust=it, decay=dc, window=wd, edge_threshold=eth, reset_on_edge=roe)
    return pol


def _replay(trace, hints, C, pol):
    """Causal replay. Returns miss count. `pol` already validated/normalized.

    Trust tracking is MODE-INDEPENDENT: whenever a page reappears, we compare
    the forecast recorded at its PREVIOUS touch against the gap that actually
    elapsed, and nudge trust toward 1 (forecast was roughly right) or toward 0
    (it wasn't). This isolates "is the runner accurate" from "did this
    particular eviction turn out fine" -- the latter is true most of the time
    under ANY reasonable policy and would otherwise falsely inflate trust.
    """
    mode = pol["mode"]
    if mode == "lru":
        trust, adaptive = 0.0, False
    elif mode == "hint":
        trust, adaptive = 1.0, False
    else:
        trust, adaptive = pol["init_trust"], True
    decay = pol.get("decay", 0.1)
    window = pol.get("window", 10)
    edge_threshold = pol.get("edge_threshold", 0.5)
    reset_on_edge = pol.get("reset_on_edge", False)
    init_trust = pol.get("init_trust", trust)

    cache = set()
    last_idx = {}
    hint_at = {}
    pending_verify = {}             # page -> (touch_time, predicted_gap)
    misses = 0
    recent = deque(maxlen=window if window >= 2 else 2)

    for t, page in enumerate(trace):
        h = hints[t]

        if page in pending_verify:
            t0, pred0 = pending_verify.pop(page)
            if adaptive:
                actual_gap = t - t0
                tol = max(3.0, 0.4 * actual_gap)
                if abs(actual_gap - pred0) <= tol:
                    trust = trust + decay * (1.0 - trust)
                else:
                    trust = trust - decay * trust

        if page in cache:
            hit = True
            last_idx[page] = t
            hint_at[page] = h
        else:
            hit = False
            misses += 1
            if len(cache) >= C:
                pages = list(cache)
                k = len(pages)
                if k == 1:
                    victim = pages[0]
                else:
                    rec_sorted = sorted(pages, key=lambda p: (last_idx[p], p))
                    rec_rank = {p: i for i, p in enumerate(rec_sorted)}
                    rec_norm = {p: (k - 1 - rec_rank[p]) / (k - 1) for p in pages}
                    remgap = {p: hint_at[p] - (t - last_idx[p]) for p in pages}
                    hint_sorted = sorted(pages, key=lambda p: (remgap[p], p))
                    hint_rank = {p: i for i, p in enumerate(hint_sorted)}
                    hint_norm = {p: hint_rank[p] / (k - 1) for p in pages}
                    combo = {p: trust * hint_norm[p] + (1.0 - trust) * rec_norm[p] for p in pages}
                    victim = max(pages, key=lambda p: (combo[p], -last_idx[p], -p))
                cache.discard(victim)
                del last_idx[victim]
                del hint_at[victim]
            cache.add(page)
            last_idx[page] = t
            hint_at[page] = h

        pending_verify[page] = (t, h)

        recent.append(0 if hit else 1)
        if adaptive and len(recent) == recent.maxlen:
            if (sum(recent) / len(recent)) >= edge_threshold and reset_on_edge:
                trust = init_trust
                recent.clear()

    return misses


def _belady_misses(trace, C):
    """Exact clairvoyant-optimal miss count (unreachable ideal reference)."""
    occ = {}
    for i, p in enumerate(trace):
        occ.setdefault(p, []).append(i)
    cache = set()
    misses = 0
    for t, p in enumerate(trace):
        if p in cache:
            continue
        misses += 1
        if len(cache) < C:
            cache.add(p)
        else:
            victim, victim_next = None, -1
            for q in cache:
                lst = occ[q]
                i = bisect_right(lst, t)
                nxt = lst[i] if i < len(lst) else 10 ** 9
                if nxt > victim_next or (nxt == victim_next and (victim is None or q < victim)):
                    victim_next, victim = nxt, q
            cache.discard(victim)
            cache.add(p)
    return misses


# ----------------------------- scoring driver -------------------------------
def main():
    if len(sys.argv) < 2:
        print("usage: evaluator.py <solution.py>")
        sys.exit(2)
    cand = sys.argv[1]
    instances = _build_instances()

    vec = []
    for inst in instances:
        C = inst["capacity"]
        real_trace, real_hints = inst["real_trace"], inst["real_hints"]
        m_base = _replay(real_trace, real_hints, C, {"mode": "lru"})
        m_opt = _belady_misses(real_trace, C)
        denom = max(1, m_base - m_opt)

        public = {"name": inst["name"], "capacity": C, "n_pages": inst["n_pages"],
                  "calib": {"n": len(inst["calib_trace"]),
                            "page": list(inst["calib_trace"]),
                            "hint": list(inst["calib_hints"])}}
        ans, st = isorun.run_candidate(cand, public, timeout=20)
        if st != "OK":
            vec.append(0.0)
            continue
        pol = _validate_policy(ans)
        if pol is None:
            vec.append(0.0)
            continue
        try:
            m_cand = _replay(real_trace, real_hints, C, pol)
        except Exception:
            vec.append(0.0)
            continue

        r = 0.1 + 0.9 * (m_base - m_cand) / denom
        if not (r == r) or r in (float("inf"), float("-inf")):
            vec.append(0.0)
            continue
        r = max(0.0, min(1.0, r))
        vec.append(r)

    ratio = sum(vec) / len(vec) if vec else 0.0
    print("Ratio: %.6f" % ratio)
    print("Vector: " + json.dumps([round(x, 6) for x in vec]))


if __name__ == "__main__":
    main()
