# TIER: strong
# The insight: the calm-season rows are generated by a berth-PRIORITY queue.
# If class c has cumulative higher-priority load P_c and own load r_c, its
# mean wait carries the capacity pole
#
#     W_c = N / ((1 - P_c) * (1 - P_c - r_c)),   N = shared numerator ~ a0*rho
#
# so the pole at utilization 1 is invisible in the calm regime yet fully
# determined by it ONCE the functional form is imposed.  Moreover the hidden
# priority ORDER is recoverable as a byproduct: under the true ordering the
# rescaled quantity
#
#     z_{i,c} = w_{i,c} * (1 - P_c(i)) * (1 - P_c(i) - r_c(i)) / rho_i
#
# is the SAME shared numerator for every class in every row, so its spread
# across classes is minimal; under any wrong ordering, mismatched
# (1-P)(1-X) factors inject systematic cross-class spread.  We therefore
# search all K! orderings for the one minimising the (mean-normalised)
# residual variance of z, fit a0 as the grand mean of z, and emit the
# closed-form pole predictors.  This generalises to rho 0.85..0.97 where the
# lowest-priority class explodes like 1/(1-rho)^2.
import sys
from itertools import permutations


def main():
    toks = sys.stdin.read().split()
    n = int(toks[0])
    K = int(toks[1])
    vals = toks[3:]
    rows = []
    idx = 0
    for _ in range(n):
        rho = float(vals[idx])
        idx += 1
        mix = [float(vals[idx + j]) for j in range(K)]
        idx += K
        w = [float(vals[idx + j]) for j in range(K)]
        idx += K
        rows.append((rho, [rho * m for m in mix], w))

    best_crit = None
    best_perm = None
    best_a0 = 0.0
    for perm in permutations(range(K)):
        zs = []
        for rho, r, w in rows:
            cum = 0.0
            for rank in range(K):
                c = perm[rank]
                z = w[c] * (1.0 - cum) * (1.0 - cum - r[c]) / rho
                zs.append(z)
                cum += r[c]
        m = sum(zs) / len(zs)
        if m <= 0:
            continue
        var = sum((z - m) ** 2 for z in zs) / len(zs)
        crit = var / (m * m)
        if best_crit is None or crit < best_crit:
            best_crit = crit
            best_perm = perm
            best_a0 = m

    out = []
    for c in range(K):
        rank = best_perm.index(c)
        higher = best_perm[:rank]
        if higher:
            q = " + ".join("r%d" % (j + 1) for j in higher)
            den = "(1 - (%s)) * (1 - (%s) - r%d)" % (q, q, c + 1)
        else:
            den = "1 - r%d" % (c + 1)
        out.append("W%d = %.8f * rho / (%s)" % (c + 1, best_a0, den))
    print("\n".join(out))


if __name__ == "__main__":
    main()
