import sys, json, math, random, isorun

# ==========================================================================
# fsx_C_0200 -- causal-discovery (Format B, isolated candidate)
# Theme: "warehouse robotics".  A fleet-telemetry system logs d process
# signals (intake rate, conveyor speed, robot utilization, queue length,
# ...).  The signals are generated by a HIDDEN structural causal model on
# a ground-truth DAG (a warehouse "influence map"): each signal is a
# linear function of its causal parents plus independent shocks, with
# EQUAL shock variance.  The candidate sees only the observational
# telemetry matrix and must emit an estimated causal DAG (directed edges).
#
# Objective: MINIMIZE the Structural Hamming Distance (SHD) between the
# emitted DAG and the hidden ground-truth DAG, averaged (via the harness
# normalizer) over a battery of warehouse graphs of increasing size and
# density.  An empty graph scores the trivial baseline (SHD == #true
# edges).  A cyclic / malformed / out-of-range answer scores 0.
#
# WHY it is open-ended: the public column order is a hidden permutation of
# the causal (topological) order, so orientation is NOT read off the
# indices; the skeleton must be recovered from (partial) correlations and
# the orientation from the equal-variance identifiability signal (source
# signals have smaller variance than their descendants).  Multiple viable
# strategies (marginal thresholding, order-k PC pruning, variance
# ordering, score-based search) trade off precision vs recall; no single
# cheap rule is optimal across the battery.
# ==========================================================================


# ----------------------------- data model ---------------------------------
NAMES = ["intake_rate", "conveyor_speed", "robot_utilization", "queue_length",
         "pick_latency", "battery_drain", "charge_cycles", "error_rate",
         "reroute_count", "dock_wait", "throughput", "backlog"]


def _gen(d, edges_topo, n, seed, sigma=1.0, wlo=0.7, whi=1.3):
    """Linear-Gaussian SCM with EQUAL shock variance, in topological order
    0..d-1 (every edge a->b has a<b).  Then relabel columns by a hidden
    permutation so the public index order is NOT the causal order."""
    rng = random.Random(seed)
    # per-edge positive weights (deterministic over the ordered edge list)
    W = {(a, b): round(rng.uniform(wlo, whi), 6) for (a, b) in edges_topo}
    parents = {j: [a for (a, b) in edges_topo if b == j] for j in range(d)}
    cols = [[0.0] * n for _ in range(d)]     # cols[topo_node][sample]
    for j in range(d):
        pa = parents[j]
        for t in range(n):
            v = 0.0
            for a in pa:
                v += W[(a, j)] * cols[a][t]
            v += rng.gauss(0.0, sigma)
            cols[j][t] = v
    # hidden permutation: public column c holds topo node perm[c]
    perm = list(range(d))
    rng.shuffle(perm)
    inv = [0] * d                            # inv[topo_node] = public column
    for c in range(d):
        inv[perm[c]] = c
    data = [[round(cols[perm[c]][t], 6) for c in range(d)] for t in range(n)]
    true_edges = sorted([inv[a], inv[b]] for (a, b) in edges_topo)
    return data, true_edges


def make_instances():
    # (d, edges in topological indices with a<b, n_samples, seed)
    specs = [
        # --- small, sparse (calibration / easy) ---
        (5, [[0, 1], [1, 2], [2, 3], [3, 4], [0, 2]], 320, 11),
        (5, [[0, 2], [1, 2], [2, 3], [2, 4]], 320, 12),
        (6, [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5]], 300, 13),
        (6, [[0, 1], [0, 2], [1, 3], [2, 3], [3, 4], [4, 5], [1, 4]], 300, 14),
        (6, [[0, 3], [1, 3], [2, 3], [3, 4], [3, 5], [0, 1]], 280, 15),
        # --- medium ---
        (7, [[0, 1], [0, 2], [1, 3], [2, 4], [3, 5], [4, 5], [5, 6], [1, 4]], 280, 16),
        (7, [[0, 2], [1, 2], [2, 3], [2, 4], [3, 5], [4, 5], [5, 6]], 260, 17),
        (7, [[0, 1], [0, 2], [0, 3], [1, 4], [2, 4], [3, 5], [4, 6], [5, 6], [1, 5]], 260, 18),
        (8, [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [0, 3], [2, 5]], 260, 19),
        (8, [[0, 2], [1, 2], [2, 4], [3, 4], [4, 6], [5, 6], [6, 7], [0, 5], [1, 3]], 240, 20),
        # --- harder / denser (held-out generalization) ---
        (8, [[0, 1], [0, 2], [1, 3], [2, 3], [1, 4], [3, 5], [4, 5], [2, 6],
             [5, 7], [6, 7], [0, 4]], 220, 21),
        (8, [[0, 1], [1, 2], [0, 3], [2, 4], [3, 4], [4, 5], [3, 6], [5, 7],
             [6, 7], [1, 5], [2, 6]], 200, 22),
    ]
    out = []
    for (d, edges, n, seed) in specs:
        data, true_edges = _gen(d, edges, n, seed)
        pub = {"names": NAMES[:d], "d": d, "n": n, "data": data}
        out.append({"public": pub, "hidden": {"true_edges": true_edges}})
    return out


# ----------------------------- scoring ------------------------------------
def _is_dag(d, edges):
    """Kahn topological sort; True iff acyclic."""
    indeg = [0] * d
    adj = [[] for _ in range(d)]
    for (a, b) in edges:
        adj[a].append(b)
        indeg[b] += 1
    q = [i for i in range(d) if indeg[i] == 0]
    seen = 0
    while q:
        u = q.pop()
        seen += 1
        for v in adj[u]:
            indeg[v] -= 1
            if indeg[v] == 0:
                q.append(v)
    return seen == d


def _shd(d, true_edges, pred_edges):
    """Standard Structural Hamming Distance over unordered pairs:
    +1 for a missing edge, +1 for an extra edge, +1 for a reversal."""
    def orient(edges):
        o = {}
        for (a, b) in edges:
            u, v = (a, b) if a < b else (b, a)
            o[(u, v)] = "fwd" if a < b else "rev"
        return o
    to = orient(true_edges)
    po = orient(pred_edges)
    pairs = set(to) | set(po)
    s = 0
    for p in pairs:
        if to.get(p) != po.get(p):
            s += 1
    return s


def score(inst, ans):
    pub = inst["public"]
    d = pub["d"]
    true_edges = [tuple(e) for e in inst["hidden"]["true_edges"]]
    if not isinstance(ans, dict) or "edges" not in ans:
        return False, 0.0
    raw = ans["edges"]
    if not isinstance(raw, list):
        return False, 0.0
    pred = []
    seen = set()
    for e in raw:
        if not isinstance(e, (list, tuple)) or len(e) != 2:
            return False, 0.0
        a, b = e
        if isinstance(a, bool) or isinstance(b, bool):
            return False, 0.0
        if not isinstance(a, int) or not isinstance(b, int):
            return False, 0.0
        if a < 0 or b < 0 or a >= d or b >= d or a == b:
            return False, 0.0
        key = (a, b)
        if key in seen or (b, a) in seen:
            return False, 0.0        # duplicate / both-directions -> not a simple DAG
        seen.add(key)
        pred.append((a, b))
    if not _is_dag(d, pred):
        return False, 0.0            # cyclic answers are infeasible
    return True, float(_shd(d, true_edges, pred))


def baseline(inst):
    # trivial construction the evaluator computes itself: the EMPTY graph,
    # whose SHD equals the number of true edges.
    return float(len(inst["hidden"]["true_edges"]))


def main():
    cand = sys.argv[1]
    insts = make_instances()
    vec = []
    for inst in insts:
        ans, stt = isorun.run_candidate(cand, inst["public"], timeout=20)
        if stt != "OK":
            vec.append(0.0)
            continue
        try:
            ok, obj = score(inst, ans)
        except Exception:
            ok = False
        if not ok:
            vec.append(0.0)
            continue
        b = baseline(inst)
        # minimization: r == 0.1 at the trivial (empty-graph) SHD; grows as
        # SHD shrinks; capped at 1.0 (an exact recovery would need SHD<=b/10).
        r = min(1.0, 0.1 * b / max(obj, 1e-12))
        vec.append(r if (r == r and 0 <= r <= 1) else 0.0)
    ratio = sum(vec) / len(vec)
    print("Ratio: %.6f" % ratio)
    print("Vector: " + json.dumps([round(x, 6) for x in vec]))


main()
