#!/usr/bin/env python3
"""
FROZEN evaluator for fsx_C_0188 -- "Traffic Signal Grid: Congestion Causal-Graph Recovery"
(family: causal-discovery; eval_form: quality-metric; MLS-Bench causal-* shape).

A city runs a network of signalised intersections.  Over many time snapshots each
intersection reports a scalar CONGESTION index (mean queue length / delay).  The
snapshots are generated by an unknown directed acyclic *flow graph*: congestion at
an intersection is a linear combination of the congestion at its UPSTREAM feeders
plus an independent local-arrival fluctuation of comparable magnitude across the
grid.  That is exactly a linear structural causal model (SCM)

        C_j = sum_{i in parents(j)} w_ij * C_i + eps_j ,   eps_j ~ N(0, sigma^2)

with a SHARED noise scale sigma (equal-variance regime -> the DAG is identifiable
from purely observational data).  The ground-truth flow DAG is known to THIS
evaluator but HIDDEN from the candidate; the intersection column labels are
RANDOMLY PERMUTED before the data is exposed, so the column index carries no
information about causal order.

The candidate designs a CAUSAL-DISCOVERY routine.  It runs as an ISOLATED
subprocess (isorun): it reads ONE JSON "public instance" from stdin and writes ONE
JSON answer (the recovered directed edges) to stdout.  It never sees the true
graph, the SCM parameters, or this evaluator's memory.

Public instance JSON (stdin):
    {
      "data":      [[float, ...], ...],   # T x p matrix: row t = congestion snapshot t
      "n_samples": int,                   # number of snapshots T
      "n_nodes":   int,                   # number of intersections p (columns of data)
      "seed":      int                    # a per-instance seed the candidate MAY use
    }

Answer JSON (stdout):  either a bare edge list, or an object with an "edges" field.
    [[i, j], ...]                         # directed edge i -> j (i is upstream of j)
    {"edges": [[i, j], ...]}              # equivalent

Quality = Structural Hamming Distance (SHD) between the recovered directed graph
and the hidden flow DAG, recomputed deterministically here.  SHD counts, over all
unordered intersection pairs {i,j}, the pairs whose directed-edge state DIFFERS
(a missing edge, an extra edge, or a reversed edge each cost 1).  Lower is better.

Per-instance normalization is an affine anchor against the evaluator's own trivial
construction -- the EMPTY graph, whose SHD equals the number E of true flow edges:

    r = clamp( 0.1 + 0.9 * (E - SHD_cand) / E , 0, 1 )

so an empty / no-op answer maps to ~0.1, a perfect recovery (SHD = 0) maps to 1.0,
and doing worse than empty pushes r below 0.1 toward 0.  An answer that raises,
mis-shapes, or names an out-of-range intersection scores exactly 0.0.  The battery
mixes grid sizes, snapshot counts and flow densities (including harder held-out
instances with few snapshots / dense flow), and the final score is the MEAN of the
per-instance r -- rewarding a discovery rule that GENERALISES rather than one tuned
to a single grid.

CLI:   python3 evaluator.py <candidate.py>
Prints:
  Ratio: <mean per-instance r, in [0,1]>
  Vector: [r_1, r_2, ...]
"""
import os
for _v in ("OPENBLAS_NUM_THREADS", "OMP_NUM_THREADS", "MKL_NUM_THREADS",
           "NUMEXPR_NUM_THREADS", "VECLIB_MAXIMUM_THREADS"):
    os.environ[_v] = "1"

import sys, json, math
import numpy as np
import isorun

CAND_TIMEOUT = 25
MAX_EDGES_FACTOR = 4        # reject answers with absurdly many edges (> factor * p^2)


# ============================ flow-DAG family (instances) ==================
def _make_dag(seed, p, target_indeg, w_lo, w_hi):
    """Generate a random linear-Gaussian equal-variance SCM on a DAG.

    Internal node labels 0..p-1 are a valid topological order (parents have
    strictly smaller index).  Returns (X, A) where X is T-agnostic here (data is
    drawn by the caller) -- actually we draw data too for determinism.
    """
    rng = np.random.default_rng(seed)
    # weighted adjacency in the INTERNAL (topological) labelling: W[i, j] != 0 => i -> j, i < j
    W = np.zeros((p, p), dtype=np.float64)
    A = np.zeros((p, p), dtype=np.int64)
    for j in range(1, p):
        prob = min(1.0, target_indeg / float(j))
        for i in range(j):
            if rng.random() < prob:
                w = rng.uniform(w_lo, w_hi)
                if rng.random() < 0.5:
                    w = -w
                W[i, j] = w
                A[i, j] = 1
    return W, A, rng


def _draw_data(W, A, rng, T, sigma):
    p = W.shape[0]
    X = np.zeros((T, p), dtype=np.float64)
    eps = rng.normal(0.0, sigma, size=(T, p))
    # topological order is 0..p-1 by construction
    for j in range(p):
        # X_j = sum_i W[i,j] X_i + eps_j  (only i < j contribute)
        if j == 0:
            X[:, j] = eps[:, j]
        else:
            X[:, j] = X[:, :j] @ W[:j, j] + eps[:, j]
    return X


def _permute(X, A, rng):
    """Randomly relabel columns so the exposed index reveals no causal order.

    Exposed column k holds internal node ``perm[k]``; the adjacency is relabeled
    consistently so that Ap[a, b] == A[perm[a], perm[b]] (edge between exposed
    labels a->b iff the corresponding internal edge exists)."""
    p = A.shape[0]
    perm = rng.permutation(p)
    Xp = X[:, perm]
    Ap = A[np.ix_(perm, perm)].copy()
    return Xp, Ap


def _build_instances():
    # (seed, p, T, target_indeg, w_lo, w_hi, sigma)
    specs = [
        (10188001, 8, 600, 1.4, 0.5, 0.8, 1.0),
        (10188002, 8, 400, 1.6, 0.4, 0.8, 1.0),
        (10188003, 10, 700, 1.4, 0.5, 0.8, 1.0),
        (10188004, 10, 450, 1.6, 0.4, 0.8, 1.0),
        (10188005, 12, 700, 1.4, 0.5, 0.8, 1.0),
        (10188006, 12, 450, 1.6, 0.4, 0.8, 1.0),
        (10188007, 10, 900, 1.3, 0.5, 0.9, 1.0),   # easier: many snapshots, sparser
        (10188008, 14, 500, 1.6, 0.4, 0.8, 1.0),   # held-out: larger grid
        (10188009, 14, 320, 1.6, 0.4, 0.8, 1.0),   # held-out+hard: few snapshots
        (10188010, 12, 340, 2.0, 0.4, 0.8, 1.0),   # held-out+hard: dense flow, few snapshots
    ]
    out = []
    for (seed, p, T, indeg, w_lo, w_hi, sigma) in specs:
        W, A, rng = _make_dag(seed, p, indeg, w_lo, w_hi)
        X = _draw_data(W, A, rng, T, sigma)
        Xp, Ap = _permute(X, A, rng)
        out.append({"name": f"grid{seed}", "X": Xp, "A": Ap, "p": p, "T": T})
    return out


# ============================ SHD (deterministic) ==========================
def _shd(A_true, A_est):
    """Structural Hamming Distance over unordered pairs of directed 0/1 adjacency
    matrices (no self loops).  Each pair whose directed-edge state differs -> 1."""
    p = A_true.shape[0]
    d = 0
    for i in range(p):
        for j in range(i + 1, p):
            t = (int(A_true[i, j]), int(A_true[j, i]))
            e = (int(A_est[i, j]), int(A_est[j, i]))
            if t != e:
                d += 1
    return d


# ============================ candidate answer handling ====================
def _valid_adj(ans, p):
    """Return a p x p int adjacency (0/1, no self loops) or None if invalid."""
    if isinstance(ans, dict):
        ans = ans.get("edges", None)
    if ans is None:
        return None
    if not isinstance(ans, (list, tuple)):
        return None
    if len(ans) > MAX_EDGES_FACTOR * p * p:
        return None
    A = np.zeros((p, p), dtype=np.int64)
    for e in ans:
        if not isinstance(e, (list, tuple)) or len(e) != 2:
            return None
        i, j = e
        if isinstance(i, bool) or isinstance(j, bool):
            return None
        if not isinstance(i, int) or not isinstance(j, int):
            # allow integral floats
            if isinstance(i, float) and float(i).is_integer():
                i = int(i)
            else:
                return None
            if isinstance(j, float) and float(j).is_integer():
                j = int(j)
            else:
                return None
        if i < 0 or i >= p or j < 0 or j >= p or i == j:
            return None
        A[i, j] = 1
    return A


def main():
    if len(sys.argv) < 2:
        print("usage: evaluator.py <candidate.py>")
        sys.exit(2)
    cand = sys.argv[1]
    instances = _build_instances()

    vec = []
    for inst in instances:
        X, A = inst["X"], inst["A"]
        p = inst["p"]
        E = int(A.sum())                    # number of true directed edges
        if E == 0:
            # degenerate guard (should not happen with these specs)
            vec.append(0.1)
            continue

        public = {
            "data": X.tolist(),
            "n_samples": int(inst["T"]),
            "n_nodes": int(p),
            "seed": int(inst["name"][4:]),
        }
        ans, st = isorun.run_candidate(cand, public, timeout=CAND_TIMEOUT)
        if st != "OK":
            vec.append(0.0)
            continue

        A_est = _valid_adj(ans, p)
        if A_est is None:
            vec.append(0.0)
            continue

        try:
            shd = _shd(A, A_est)
        except Exception:
            vec.append(0.0)
            continue

        r = 0.1 + 0.9 * (E - shd) / float(E)
        if r < 0.0:
            r = 0.0
        elif r > 1.0:
            r = 1.0
        vec.append(float(r))

    ratio = sum(vec) / len(vec)

    print("Ratio: %.6f" % ratio)
    print("Vector: " + json.dumps([round(v, 6) for v in vec]))


if __name__ == "__main__":
    main()
