#!/usr/bin/env python3
"""
FROZEN evaluator for fsx_A_0851 -- "Quantize a stream hiding on a curve"
(family: online-manifold-quantizer; format B, quality-metric).

THEME.  A stream of T vectors in R^D arrives in R rounds (round_of[i] tells which round
point i belongs to; rounds are contiguous and increasing).  Every point actually sits
(plus small isotropic noise) on a hidden 1-D nonlinear manifold: a spiral
  x(tau) = tau*cos(2*pi*f*tau)*scale,  y(tau) = tau*sin(2*pi*f*tau)*scale,   tau in [0,1]
embedded through a fixed random orthogonal D x D rotation (so the two "signal"
coordinates are not axis-aligned and cannot be spotted by looking at per-axis variance).
tau is NEVER revealed. Which sub-range of tau is active SLIDES from round to round (round
0 samples tau from a window near 0, the last round samples a window near 1), so the
region of ambient space the stream currently occupies drifts over the R rounds -- while
the spiral's early/late windings still sit ambiently close to each other (a point one
full winding away is close in Euclidean space but far along the curve).

LATENT-MANIFOLD-EXPLOIT (mechanism 1).  Because winds of the spiral pass close to each
other in R^D, the point that is Euclidean-nearest to a given point is very often NOT its
nearest neighbour along the curve -- ambient distance is a bad proxy for the manifold's
intrinsic (arc-length) coordinate.

ONLINE-CODEBOOK-ADAPTATION (mechanism 2, GENUINELY causal).  The candidate program is
invoked ONCE PER ROUND, EACH TIME in a *fresh, independent, isolated subprocess* that
receives ONLY that round's own new points -- it never sees future rounds' data (there is
no way to "peek ahead" because later rounds' points are generated by the evaluator and
handed to a brand-new process only after the current round's codebook has already been
committed and scored), and it carries NO memory between rounds except whatever it hands
back as its codebook, which the evaluator echoes to it next round as `prev_codebook`.
Submitting one codebook of exactly K codewords per round is therefore a genuinely online
decision, not a batch fit over the whole stream re-labelled by round.

REGRET-CONTROLLED-UPDATE (mechanism 3, the innovation hook).  Moving codewords between
consecutive rounds is metered: the total Euclidean movement summed over all K slots from
round r-1 to round r may not exceed `move_budget[r]`. A policy that re-fits a fresh
ambient codebook to EACH round's own narrow window and tries to drag all K slots there
runs the budget dry and permanently lags the drift once it has moved on. The winning move
is to recognise, from each round's own data plus the codebook state carried forward, that
this is one continuous 1-D curve being sampled through a sliding window, and to spend the
scarce movement budget extending coverage along the curve's own intrinsic direction
instead of chasing the raw ambient centroid of whatever is newly visible.

CANDIDATE CONTRACT (isolated stdin -> stdout program, called R times per instance).
  stdin (one call per round r=0..R-1): ONE JSON object:
            {"instance": str, "r": int, "R": int, "D": int, "K": int,
             "points": [[x_0..x_{D-1}], ...],   # ONLY round r's own new points
             "prev_codebook": [[..K rows..]] or null,   # null iff r==0
             "move_budget": float or null}      # null iff r==0 (free initial placement);
                                                  # else caps total per-slot movement from
                                                  # prev_codebook to this round's codebook
  stdout (each call): ONE JSON object:
            {"codebook": [[c_0..c_{D-1}], ... K rows],
             "assign":   [k_0 ... k_{n_r-1}]}    # codeword index reconstructing each of
                                                   # THIS round's points, in input order

  VALID iff, for every round: `codebook` has exactly K length-D lists of finite numbers
  with |value| <= BOUND; `assign` has exactly n_r integers in [0,K); and (when r>=1)
  sum_k ||codebook[k] - prev_codebook[k]||_2 <= move_budget + 1e-6. Any violation, crash,
  timeout, or non-JSON on ANY round -> 0.0 on the WHOLE instance.

SCORING (deterministic; no wall-time). Reconstruction error F(cand) = mean over all T
points (pooled across rounds) of ||point - codebook[assign]||^2 using that round's own
committed codebook (LOWER is better).
    F_base = mean squared error of the round-0 mean, repeated K times and never revisited
             again (an honestly-online "commit once, never adapt" do-nothing reference).
    LB     = 0.8 * (a per-round-INDEPENDENT best-effort K-means cost computed by the
             evaluator with FULL knowledge of that round's own points -- something no
             online policy has in advance -- ignoring slot-continuity and the movement
             budget entirely) -- an intentionally unreachable lower bound (deflated by
             20% for extra safety margin).
    r = clamp( 0.1 + 0.9 * (F_base - F_cand) / (F_base - LB), 0, 1 )
  The round-0-mean-forever codebook scores exactly 0.1. Because LB additionally assumes
  full foreknowledge of each round's own data that no online candidate ever receives (and
  is further deflated), no admissible strategy can reach it, so r < 1 always. Final score
  = mean of r over 10 fixed seeded instances.

ISOLATION. Each round's call is a FRESH bwrap-SANDBOXED SUBPROCESS via
`isorun.run_candidate`; it only ever sees that round's own points plus the codebook it
returned last round -- never any other round's raw data, never the evaluator's internals.

CLI: python3 evaluator.py <solution.py>
"""
import sys, json, math
import numpy as np
import isorun

BOUND = 1000.0


# ----------------------------- deterministic instance construction ---------------------
def _orthogonal(D, rng):
    A = rng.standard_normal((D, D))
    Q, Rm = np.linalg.qr(A)
    d = np.sign(np.diag(Rm))
    d[d == 0] = 1.0
    return Q * d


def _spiral_xy(tau, f_turns, scale_xy):
    ang = 2.0 * math.pi * f_turns * tau
    return tau * math.cos(ang) * scale_xy, tau * math.sin(ang) * scale_xy


def _round_windows(R, width):
    if R == 1:
        return [(0.0, 1.0)]
    span = 1.0 - width
    out = []
    for r in range(R):
        lo = r * span / (R - 1)
        hi = min(1.0, lo + width)
        out.append((lo, hi))
    return out


def _kmeans(points, K, rng, iters=35, restarts=3):
    """Deterministic (given rng) Lloyd's algorithm with k-means++ seeding; returns
    (centers, mean_sq_cost)."""
    n = points.shape[0]
    if n == 0:
        return np.zeros((K, points.shape[1] if points.ndim == 2 else 1)), 0.0
    D = points.shape[1]
    if n <= K:
        centers = np.array([points[i % n] for i in range(K)], dtype=float)
        return centers, 0.0
    best_cost, best_centers = None, None
    for _ in range(restarts):
        centers = np.zeros((K, D))
        idx0 = int(rng.randint(0, n))
        centers[0] = points[idx0]
        d2 = np.sum((points - centers[0]) ** 2, axis=1)
        for k in range(1, K):
            s = d2.sum()
            probs = d2 / s if s > 1e-12 else np.full(n, 1.0 / n)
            idx = int(rng.choice(n, p=probs))
            centers[k] = points[idx]
            nd2 = np.sum((points - centers[k]) ** 2, axis=1)
            d2 = np.minimum(d2, nd2)
        for _ in range(iters):
            dists = ((points[:, None, :] - centers[None, :, :]) ** 2).sum(axis=2)
            assign = np.argmin(dists, axis=1)
            newc = centers.copy()
            for k in range(K):
                mask = assign == k
                if mask.any():
                    newc[k] = points[mask].mean(axis=0)
            if np.allclose(newc, centers, atol=1e-10):
                centers = newc
                break
            centers = newc
        dists = ((points[:, None, :] - centers[None, :, :]) ** 2).sum(axis=2)
        cost = float(np.min(dists, axis=1).mean())
        if best_cost is None or cost < best_cost:
            best_cost, best_centers = cost, centers.copy()
    return best_centers, best_cost


def _build_one(name, seed, D, K, R, T, f_turns, scale_xy, noise_sigma, width, budget_frac):
    rng = np.random.RandomState(seed)
    Q = _orthogonal(D, rng)
    windows = _round_windows(R, width)
    per_round = T // R
    pts = []
    round_of = []
    for r in range(R):
        n_r = per_round if r < R - 1 else T - per_round * (R - 1)
        lo, hi = windows[r]
        taus = rng.uniform(lo, hi, size=n_r)
        for tau in taus:
            x, y = _spiral_xy(float(tau), f_turns, scale_xy)
            sig = np.zeros(D)
            sig[0] = x
            sig[1] = y
            p = Q.dot(sig) + rng.normal(0.0, noise_sigma, size=D)
            pts.append(p)
            round_of.append(r)
    pts = np.array(pts)
    round_of = np.array(round_of, dtype=int)

    # movement budgets, scaled to the ambient shift between consecutive window centers
    centers_amb = []
    for lo, hi in windows:
        tm = 0.5 * (lo + hi)
        x, y = _spiral_xy(tm, f_turns, scale_xy)
        sig = np.zeros(D)
        sig[0] = x
        sig[1] = y
        centers_amb.append(Q.dot(sig))
    move_budget = [0.0] * R
    for r in range(1, R):
        shift = float(np.linalg.norm(centers_amb[r] - centers_amb[r - 1]))
        move_budget[r] = max(1e-6, budget_frac * shift * K)

    points_by_round = [pts[round_of == r].tolist() for r in range(R)]

    # F_base: an honestly ONLINE do-nothing reference -- commit the round-0 mean once,
    # never revisit it (no candidate needs future rounds' data to reproduce this).
    mean0 = np.array(points_by_round[0]).mean(axis=0)
    f_base = float(np.mean(np.sum((pts - mean0) ** 2, axis=1)))

    # LB: per-round-INDEPENDENT best-effort k-means, computed with FULL knowledge of
    # that round's own points (something no genuinely online policy has in advance),
    # ignoring the persistent-slot identity and movement budget entirely, deflated 20%
    # for safety margin. Deliberately unreachable.
    lb_rng = np.random.RandomState(seed ^ 0x5EED)
    total_cost = 0.0
    for r in range(R):
        rp = np.array(points_by_round[r])
        _, cost = _kmeans(rp, K, lb_rng)
        total_cost += cost * rp.shape[0]
    lb_raw = total_cost / T
    lb = 0.8 * lb_raw

    return {
        "name": name, "D": D, "K": K, "R": R, "T": int(T),
        "round_of": round_of.tolist(),
        "points": pts.tolist(),
        "points_by_round": points_by_round,
        "move_budget": move_budget,
        "_f_base": f_base, "_lb": lb,
    }


def _build_instances():
    # (name, seed, D, K, R, T, f_turns, scale_xy, noise_sigma, width, budget_frac)
    # Base geometry (D, K, R, T, f_turns, scale_xy, noise_sigma, width, budget_frac) is
    # held in a regime empirically verified (against BOTH reference solutions, per-round,
    # via the genuinely-online protocol) to reward the intrinsic-coordinate + targeted-
    # relocation insight over the round-local warm-started recipe; only the instance seed
    # (which drives the random rotation, the noise draw, and the per-round sample split)
    # varies across the 10 held-out instances.
    base = (6, 8, 5, 500, 1.6, 6.0, 0.15, 0.30, 0.08)
    seeds = [8519, 8503, 8549, 8552, 8525, 8543, 8508, 8544, 8517, 8509]
    specs = [(f"spiral{i+1:02d}", s) + base for i, s in enumerate(seeds)]
    out = []
    for name, seed, D, K, R, T, f_turns, scale_xy, noise_sigma, width, budget_frac in specs:
        out.append(_build_one(name, seed, D, K, R, T, f_turns, scale_xy, noise_sigma,
                               width, budget_frac))
    return out


# ----------------------------- per-round validation -------------------------
def _valid_round_answer(D, K, n_r, prev_codebook, budget, answer):
    """Validate ONE round's reply. Returns (codebook, assign) or None."""
    if not isinstance(answer, dict):
        return None
    cb = answer.get("codebook")
    assign = answer.get("assign")
    if not isinstance(cb, list) or len(cb) != K:
        return None
    rows = []
    for word in cb:
        if not isinstance(word, list) or len(word) != D:
            return None
        row = []
        for v in word:
            if isinstance(v, bool) or not isinstance(v, (int, float)):
                return None
            fv = float(v)
            if not math.isfinite(fv) or abs(fv) > BOUND:
                return None
            row.append(fv)
        rows.append(row)
    if not isinstance(assign, list) or len(assign) != n_r:
        return None
    out_assign = []
    for v in assign:
        if isinstance(v, bool) or not isinstance(v, int):
            return None
        if v < 0 or v >= K:
            return None
        out_assign.append(v)
    if prev_codebook is not None:
        tot = 0.0
        for k in range(K):
            a, b = rows[k], prev_codebook[k]
            tot += math.sqrt(sum((a[d] - b[d]) ** 2 for d in range(D)))
        if tot > budget + 1e-6:
            return None
    return rows, out_assign


# ----------------------------- scoring driver (genuinely ONLINE) ------------
def main():
    """The candidate is invoked ONCE PER ROUND, in a FRESH isolated subprocess each
    time -- it never receives future rounds' points and carries no memory between
    calls except whatever it chooses to encode into the codebook it hands back (which
    is echoed to it next round as `prev_codebook`). This makes 'batch-fit everything at
    once' structurally unavailable: no single call ever sees more than one round's own
    points."""
    if len(sys.argv) < 2:
        print("usage: evaluator.py <solution.py>")
        sys.exit(2)
    cand = sys.argv[1]
    instances = _build_instances()

    vec = []
    for inst in instances:
        D, K, R = inst["D"], inst["K"], inst["R"]
        move_budget = inst["move_budget"]
        prev_codebook = None
        total_err = 0.0
        ok = True
        for r in range(R):
            rp = inst["points_by_round"][r]
            n_r = len(rp)
            payload = {"instance": inst["name"], "r": r, "R": R, "D": D, "K": K,
                       "points": [list(p) for p in rp],
                       "prev_codebook": [list(c) for c in prev_codebook] if prev_codebook else None,
                       "move_budget": None if r == 0 else move_budget[r]}
            ans, st = isorun.run_candidate(cand, payload, timeout=20)
            if st != "OK":
                ok = False
                break
            try:
                budget = None if r == 0 else move_budget[r]
                valid = _valid_round_answer(D, K, n_r, prev_codebook, budget, ans)
            except Exception:
                valid = None
            if valid is None:
                ok = False
                break
            cb, assign = valid
            for i in range(n_r):
                p = rp[i]
                cw = cb[assign[i]]
                total_err += sum((p[d] - cw[d]) ** 2 for d in range(D))
            prev_codebook = cb
        if not ok:
            vec.append(0.0)
            continue
        f_cand = total_err / inst["T"]
        f_base, lb = inst["_f_base"], inst["_lb"]
        denom = f_base - lb
        if denom <= 1e-9:
            r_score = 1.0 if f_cand <= lb + 1e-9 else 0.1
        else:
            r_score = 0.1 + 0.9 * (f_base - f_cand) / denom
        if not (r_score == r_score) or r_score in (float("inf"), float("-inf")):
            r_score = 0.0
        r_score = max(0.0, min(1.0, r_score))
        vec.append(r_score)

    ratio = sum(vec) / len(vec) if vec else 0.0
    print("Ratio: %.6f" % ratio)
    print("Vector: " + json.dumps([round(x, 6) for x in vec]))


if __name__ == "__main__":
    main()
