# TIER: strong
# The insight: the exposure log the recommender actually acted on is GIVEN,
# so the organic component does not have to be guessed from the confounded
# (t, e) trend alone -- it can be REGRESSED OUT. Model engagement as
# additive in the two mechanisms the story states:
#   e(t) = O0 + O1*t          (organic: baseline + honest drift)
#         + ALPHA*x(t)        (induced: exposure's own causal lift)
#         + noise
# and fit ALL THREE constants at once with one multiple linear regression,
# e ~ 1 + t + x, on the logged (t, x, e) triples. Because within the logged
# window x(t) also carries variation that ISN'T explained by t alone (the
# recommender's feedback reacts to noisy period-to-period engagement, and an
# exogenous shock also perturbs exposure), the regressor matrix [1, t, x] is
# well-conditioned: the t-coefficient and the x-coefficient are separately
# identifiable. This isolates the genuine organic drift from the induced
# exposure effect *within the very data generated by the feedback loop* --
# no separate experiment needed, because the "experiment" -- the
# recommender's own varying push -- is already logged.
#
# The result generalizes correctly once exposure is set by intervention in
# the held-out period, because the fitted equation uses the CORRECT causal
# structure (both t and x as separate regressors) instead of a single
# blended time trend.
import sys


def _solve3(A, b):
    """Gaussian elimination with partial pivoting for a 3x3 system."""
    M = [row[:] + [b[i]] for i, row in enumerate(A)]
    for col in range(3):
        piv = max(range(col, 3), key=lambda r: abs(M[r][col]))
        M[col], M[piv] = M[piv], M[col]
        pv = M[col][col]
        if abs(pv) < 1e-12:
            pv = 1e-12
        M[col] = [v / pv for v in M[col]]
        for r in range(3):
            if r != col:
                f = M[r][col]
                M[r] = [M[r][k] - f * M[col][k] for k in range(4)]
    return M[0][3], M[1][3], M[2][3]


def main():
    data = sys.stdin.read().split()
    if not data:
        print("0.0"); return
    tid, n_train = int(data[0]), int(data[1])
    idx = 2
    rows = []
    for i in range(n_train):
        tt = float(data[idx + 3 * i])
        x = float(data[idx + 3 * i + 1])
        e = float(data[idx + 3 * i + 2])
        rows.append((tt, x, e))

    n = len(rows)
    St = Sx = Se = Stt = Sxx = Stx = Ste = Sxe = 0.0
    for tt, x, e in rows:
        St += tt; Sx += x; Se += e
        Stt += tt * tt; Sxx += x * x; Stx += tt * x
        Ste += tt * e; Sxe += x * e

    A = [[n, St, Sx], [St, Stt, Stx], [Sx, Stx, Sxx]]
    b = [Se, Ste, Sxe]
    a0, a1, a2 = _solve3(A, b)

    print("%.10g + %.10g * t + %.10g * x" % (a0, a1, a2))


if __name__ == "__main__":
    main()
