#!/usr/bin/env python3
"""Instance generator for "Maze Treasure Collection (time-budgeted)".

Usage:
    python3 gen.py <seed>

Writes one instance to stdout in the format described in context.md:

    H W T
    (H lines, each a string of length W over the alphabet {'#','.','S'})
    K
    (K lines, each "r c v" : a treasure of value v at floor cell (r,c))

A maze on an H x W grid: '#' is a wall, '.' is open floor, 'S' is the unique
start cell (also open floor). The agent starts at 'S' and may move U/D/L/R for
at most T steps, never onto a wall or off the grid. K treasures sit on open
cells; stepping onto a treasure cell collects its value once. The instance is
laid out so that treasures are spread across the maze and T is too small to
collect everything -- you must choose which prizes are worth the detour. This is
the budgeted prize-collecting (orienteering) regime where a plain greedy
"walk to the nearest treasure" leaves a lot of value on the table.

The maze is generated by randomized DFS carving (so it is a connected,
corridor-rich maze with guaranteed reachability between open cells), then a
fraction of extra walls is knocked down to create loops (shortcuts), which is
what makes the routing decision non-trivial.
"""
import sys
import random


def main() -> None:
    if len(sys.argv) < 2:
        sys.stderr.write("usage: gen.py <seed>\n")
        sys.exit(1)
    seed = int(sys.argv[1])
    rng = random.Random(0xA1E_0007 ^ (seed * 2654435761 & 0xFFFFFFFF))

    # Grid size (odd dimensions make the DFS maze carving clean). H,W in [21,41].
    H = rng.randrange(21, 42, 2)
    W = rng.randrange(21, 42, 2)

    # grid[r][c] = True means WALL, False means open floor.
    wall = [[True] * W for _ in range(H)]

    # Randomized-DFS maze carving on the odd lattice (cells at even coords).
    def carve(sr, sc):
        stack = [(sr, sc)]
        wall[sr][sc] = False
        while stack:
            r, c = stack[-1]
            dirs = [(-2, 0), (2, 0), (0, -2), (0, 2)]
            rng.shuffle(dirs)
            advanced = False
            for dr, dc in dirs:
                nr, nc = r + dr, c + dc
                if 0 <= nr < H and 0 <= nc < W and wall[nr][nc]:
                    wall[r + dr // 2][c + dc // 2] = False
                    wall[nr][nc] = False
                    stack.append((nr, nc))
                    advanced = True
                    break
            if not advanced:
                stack.pop()

    carve(0, 0)

    # Knock down a fraction of interior walls to create loops / shortcuts.
    extra = rng.uniform(0.04, 0.12)
    for r in range(1, H - 1):
        for c in range(1, W - 1):
            if wall[r][c] and rng.random() < extra:
                wall[r][c] = False

    open_cells = [(r, c) for r in range(H) for c in range(W) if not wall[r][c]]
    # Start cell: pick a random open cell.
    sr, sc = rng.choice(open_cells)

    # Time budget: enough to roam, but far short of covering the whole maze.
    # The number of open cells bounds a full sweep; we give a modest fraction.
    nopen = len(open_cells)
    T = rng.randint(int(0.6 * nopen), int(1.2 * nopen))
    T = max(T, 30)

    # Treasures: place K of them on open cells other than the start, with values.
    K = rng.randint(int(0.20 * nopen), int(0.40 * nopen))
    candidates = [p for p in open_cells if p != (sr, sc)]
    rng.shuffle(candidates)
    K = min(K, len(candidates))
    chosen = candidates[:K]
    treasures = []
    for (r, c) in chosen:
        # values are skewed: many small, a few large, so the choice matters.
        if rng.random() < 0.15:
            v = rng.randint(50, 100)
        else:
            v = rng.randint(1, 20)
        treasures.append((r, c, v))

    # Emit.
    lines = []
    lines.append(f"{H} {W} {T}")
    for r in range(H):
        row = []
        for c in range(W):
            if (r, c) == (sr, sc):
                row.append("S")
            elif wall[r][c]:
                row.append("#")
            else:
                row.append(".")
        lines.append("".join(row))
    lines.append(str(len(treasures)))
    for (r, c, v) in treasures:
        lines.append(f"{r} {c} {v}")
    sys.stdout.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
