#!/usr/bin/env python3
"""go-judge REST API shim that needs NO user namespaces. V2: + core pinning.

V2 (timing fidelity, 2026-08-19): identical semantics to gojudge_shim.py plus
OPTIONAL per-run CPU-core pinning for faithful timing under concurrency.
  SHIM_PIN_CORES   -- "" (off, default: byte-identical behavior to v1),
                      or an explicit core list "4-15" / "4,5,8-11".
                      Every sandboxed child (compile, solution, checker,
                      interactor) is pinned via sched_setaffinity to a core
                      group ACQUIRED from this pool for the duration of the
                      run, so concurrent submissions never time-share a core
                      and measured cpu time is contention-free. Cores must be
                      inside the job's cgroup cpuset. Pool acquisition for a
                      request's cmds is atomic (no partial-hold deadlock with
                      interactive pipeMapping pairs).
  SHIM_CORES_PER_RUN -- cores per group (default 1; single-threaded judged
                      code needs exactly 1).
  Run the shim/node/driver processes themselves on DISJOINT cores (taskset
  the starter) so infra never runs on judged cores.

Drop-in replacement for the go-judge binary in the FrontierCS judge stack, for
clusters where unprivileged user namespaces are disabled (della since
2026-07-28: user.max_user_namespaces=0, so go-judge's clone(CLONE_NEWUSER)
dies with ENOSPC). The node judge (Frontier-CS/algorithmic) is not modified at
all -- this server speaks the exact API subset it uses:

    GET    /version          POST /run          DELETE /file/:id
    GET    /file/:id         POST /file (multipart, dead path in practice)

Fidelity notes (matching the go-judge v1.11.1 behavior OBSERVED on this
cluster, where cgroups were unavailable and go-judge already ran in its
rlimit/rusage fallback mode):
  - cpuLimit  -> RLIMIT_CPU (ceil seconds); SIGXCPU or cpu>limit => "Time Limit Exceeded"
  - clockLimit (else 2x cpu) -> wall timer; expiry kills the process group => TLE
  - memoryLimit -> RLIMIT_AS when addressSpaceLimit else RLIMIT_DATA
    (=> MLE surfaces as "Nonzero Exit Status"/"Signalled", same as observed)
  - stackLimit -> RLIMIT_STACK
  - memory reported = rusage ru_maxrss (bytes); runTime/time = cpu ns
  - args[0] with no '/' resolves against the sandbox workdir (NO PATH search)
  - collector files ({"name","max"}) truncate at max; overflow closes the pipe
    (child gets SIGPIPE) and yields "Output Limit Exceeded"
  - copyOut names that are collectors are a silent no-op (compile calls do this)
  - copyOutCached -> opaque fileId, reusable as copyIn {"fileId"} (mode 0755)
  - pipeMapping between two concurrent cmds (interactive problems) via os.pipe()

NOT provided (documented divergence): filesystem/pid/net isolation. Submitted
code runs as the calling user with normal FS access. Use ONLY for code
generated by our own models (same trust level as the bwrap-less research
track), never for adversarial third-party submissions.

Usage: gojudge_shim.py [-http-addr 127.0.0.1:5050] [-dir /tmp/gj-store]
                       [-calibrate-only]
       (unrecognized go-judge flags like -parallelism/-cgroup-prefix are
        accepted and ignored so the starter can pass the same argv)

Timing robustness (2026-08-03):
  SHIM_TLE_RETRY=1 (default ON): single-cmd runs that end TLE with
      cpu < SHIM_TLE_RETRY_FACTOR (1.25) x cpuLimit are rerun once; the retry
      is kept iff it is no longer TLE. Retries logged to stderr.
  Node speed calibration at startup (~1s deterministic loop): ops/sec and the
      factor vs a hardcoded ailab-EPYC reference are printed and exposed in
      GET /version (nodeSpeedCalibration). Measurement only -- no limit scaling.
      `-calibrate-only` prints the calibration JSON and exits (use it on an
      ailab node to re-baseline AILAB_EPYC_REF_OPS_PER_SEC).
"""

import json
import os
import re
import resource
import shutil
import signal
import subprocess
import sys
import threading
import time
import uuid
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

STORE_DIR = None
STORE_LOCK = threading.Lock()
STORE = {}  # fileId -> path

NS = 1_000_000_000

# ---------------------------------------------------------------------------
# Timing robustness (2026-08-03)
# ---------------------------------------------------------------------------
# (a) Borderline-TLE retry. Timing-borderline solutions flip TLE across CPU
# generations (measured: the same FCS code runs 1.44s on an old Xeon vs <1.0s
# limit-passing on an ailab EPYC). Mirror real judges' rerun policy: when a
# SINGLE-cmd run (never interactive pipeMapping pairs) ends "Time Limit
# Exceeded" with cpu_ns < SHIM_TLE_RETRY_FACTOR x cpuLimit, rerun ONCE in a
# fresh workdir and keep the better outcome (retry kept iff it is no longer
# TLE). Retries are logged to stderr. SHIM_TLE_RETRY=0 disables.
SHIM_TLE_RETRY = os.environ.get("SHIM_TLE_RETRY", "1").lower() not in (
    "0", "false", "no", "")
SHIM_TLE_RETRY_FACTOR = float(os.environ.get("SHIM_TLE_RETRY_FACTOR", "1.25"))

# (b) Node speed calibration. A fixed ~1s deterministic CPU loop is timed at
# startup and compared against a hardcoded ailab-EPYC reference so every eval
# log records the node's speed class (factor >1 = faster than reference).
# MEASUREMENT ONLY: limits are NOT scaled by default.
# Reference: della login EPYC 7H12 (Zen2) measures ~3.12e6 ops/s under
# CPython 3.12; ailab EPYC (H200 hosts) is the pinned FCS eval platform --
# re-baseline by running `gojudge_shim.py -calibrate-only` there and pasting
# the printed opsPerSec here. Loop speed depends on the CPython version too,
# so re-baseline if the deploy interpreter changes.
AILAB_EPYC_REF_OPS_PER_SEC = 6.269e6  # ailab H200-host EPYC, measured 2026-08-03 (job 11964225)

NODE_CALIB = {}  # filled by _calibrate_node_speed() in main()


# ---------------------------------------------------------------------------
# V2: per-run core pinning pool
# ---------------------------------------------------------------------------
def _parse_cores(spec):
    cores = []
    for part in spec.split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            a, b = part.split("-", 1)
            cores.extend(range(int(a), int(b) + 1))
        else:
            cores.append(int(part))
    return sorted(set(cores))


class CorePool:
    """Atomic multi-group acquisition of disjoint core groups."""

    def __init__(self, cores, per_run):
        self.groups = [tuple(cores[i:i + per_run])
                       for i in range(0, len(cores) - per_run + 1, per_run)]
        self.free = list(self.groups)
        self.cv = threading.Condition()

    def acquire(self, n):
        with self.cv:
            while len(self.free) < n:
                self.cv.wait()
            return [self.free.pop() for _ in range(n)]

    def release(self, groups):
        with self.cv:
            self.free.extend(groups)
            self.cv.notify_all()


SHIM_PIN_CORES = os.environ.get("SHIM_PIN_CORES", "").strip()
SHIM_CORES_PER_RUN = int(os.environ.get("SHIM_CORES_PER_RUN", "1"))
CORE_POOL = None
if SHIM_PIN_CORES:
    _cores = _parse_cores(SHIM_PIN_CORES)
    if len(_cores) >= 2 * SHIM_CORES_PER_RUN:
        CORE_POOL = CorePool(_cores, SHIM_CORES_PER_RUN)
    else:
        sys.stderr.write("[gojudge-shim-v2] SHIM_PIN_CORES=%r too small "
                         "(<2 groups); pinning DISABLED\n" % SHIM_PIN_CORES)


def _calibrate_node_speed(target_seconds=1.0):
    """Time a deterministic 64-bit xorshift loop for ~target_seconds of CPU
    time; returns {opsPerSec, seconds, refOpsPerSec, speedFactor}."""
    x = 88172645463325252
    ops = 0
    t0 = time.process_time()
    while time.process_time() - t0 < target_seconds:
        for _ in range(100_000):
            x ^= (x << 13) & 0xFFFFFFFFFFFFFFFF
            x ^= x >> 7
            x ^= (x << 17) & 0xFFFFFFFFFFFFFFFF
        ops += 100_000
    dt = time.process_time() - t0
    ops_per_sec = ops / dt if dt > 0 else 0.0
    return {
        "opsPerSec": round(ops_per_sec, 1),
        "seconds": round(dt, 3),
        "refOpsPerSec": AILAB_EPYC_REF_OPS_PER_SEC,
        "speedFactor": round(ops_per_sec / AILAB_EPYC_REF_OPS_PER_SEC, 4),
        "checksum": x & 0xFFFF,  # consume x; deterministic given loop count
    }


def _new_id():
    return uuid.uuid4().hex


def store_put(src_path):
    fid = _new_id()
    dst = os.path.join(STORE_DIR, fid)
    shutil.copy2(src_path, dst)
    os.chmod(dst, 0o755)
    with STORE_LOCK:
        STORE[fid] = dst
    return fid


def store_put_bytes(data):
    fid = _new_id()
    dst = os.path.join(STORE_DIR, fid)
    with open(dst, "wb") as f:
        f.write(data)
    os.chmod(dst, 0o755)
    with STORE_LOCK:
        STORE[fid] = dst
    return fid


def store_get(fid):
    with STORE_LOCK:
        return STORE.get(fid)


def store_del(fid):
    with STORE_LOCK:
        path = STORE.pop(fid, None)
    if path:
        try:
            os.unlink(path)
        except OSError:
            pass
        return True
    return False


class CollectorReader(threading.Thread):
    """Reads a pipe up to max_bytes; on overflow closes the read end (child
    gets SIGPIPE / write error, like go-judge aborting on OLE)."""

    def __init__(self, rfd, max_bytes):
        super().__init__(daemon=True)
        self.rfd = rfd
        self.max = max_bytes
        self.data = b""
        self.overflow = False

    def run(self):
        chunks = []
        got = 0
        try:
            while True:
                chunk = os.read(self.rfd, 65536)
                if not chunk:
                    break
                got += len(chunk)
                if got > self.max:
                    keep = len(chunk) - (got - self.max)
                    if keep > 0:
                        chunks.append(chunk[:keep])
                    self.overflow = True
                    break
                chunks.append(chunk)
        except OSError:
            pass
        finally:
            try:
                os.close(self.rfd)
            except OSError:
                pass
        self.data = b"".join(chunks)


def _preexec(cpu_ns, mem_bytes, stack_bytes, addr_space, pin_cores=None):
    def fn():
        os.setsid()
        if pin_cores:
            try:
                os.sched_setaffinity(0, pin_cores)
            except OSError:
                pass
        if cpu_ns:
            secs = max(1, -(-int(cpu_ns) // NS))  # ceil
            resource.setrlimit(resource.RLIMIT_CPU, (secs, secs + 1))
        if mem_bytes:
            which = resource.RLIMIT_AS if addr_space else resource.RLIMIT_DATA
            try:
                resource.setrlimit(which, (int(mem_bytes), int(mem_bytes)))
            except (ValueError, OSError):
                pass
        if stack_bytes:
            try:
                resource.setrlimit(
                    resource.RLIMIT_STACK, (int(stack_bytes), int(stack_bytes))
                )
            except (ValueError, OSError):
                pass
        # guard the shared filesystem against runaway single files (go-judge
        # capped the whole sandbox at a 128m tmpfs; per-file 256M is the
        # closest userns-free analogue)
        try:
            resource.setrlimit(resource.RLIMIT_FSIZE, (1 << 28, 1 << 28))
        except (ValueError, OSError):
            pass

    return fn


class PreparedCmd:
    __slots__ = (
        "workdir", "argv", "env", "stdin_file", "collectors", "pipe_fds",
        "copy_out", "copy_out_cached", "cpu_ns", "clock_ns", "proc", "err",
        "wall_killed", "collector_names", "pin_cores",
    )


def prepare_cmd(cmd, workdir):
    """Materialize copyIn + fd plan for one cmd. Returns PreparedCmd or an
    error-status dict."""
    p = PreparedCmd()
    p.workdir = workdir
    p.err = None
    p.wall_killed = False
    p.pin_cores = None

    for name, spec in (cmd.get("copyIn") or {}).items():
        dst = os.path.join(workdir, name)
        os.makedirs(os.path.dirname(dst), exist_ok=True) if "/" in name else None
        if "fileId" in spec:
            src = store_get(spec["fileId"])
            if src is None:
                return {"status": "File Error",
                        "error": "copyIn fileId not found: %s" % spec["fileId"]}
            shutil.copy2(src, dst)
            os.chmod(dst, 0o755)
        else:
            content = spec.get("content", "")
            data = content.encode() if isinstance(content, str) else content
            with open(dst, "wb") as f:
                f.write(data)

    argv = list(cmd.get("args") or [])
    if not argv:
        return {"status": "File Error", "error": "empty args"}
    if "/" not in argv[0]:
        cand = os.path.join(workdir, argv[0])
        if os.path.isfile(cand):
            argv[0] = cand
        elif not shutil.which(argv[0], path="") and not os.path.isabs(argv[0]):
            # keep as-is; exec will fail -> File Error, matching go-judge's
            # no-PATH-search semantics (absolute paths like /usr/bin/g++ pass
            # through untouched)
            argv[0] = cand
    p.argv = argv
    p.env = dict(e.split("=", 1) for e in (cmd.get("env") or []) if "=" in e)

    files = cmd.get("files") or []
    p.stdin_file = None
    p.collectors = {}   # fd -> (name, max)
    p.pipe_fds = {}     # fd -> None placeholder (filled by pipeMapping)
    for i, spec in enumerate(files):
        if spec is None:
            p.pipe_fds[i] = None
        elif "content" in spec and "name" not in spec:
            sf = os.path.join(workdir, ".stdin_%d" % i)
            content = spec.get("content", "")
            data = content.encode() if isinstance(content, str) else content
            with open(sf, "wb") as f:
                f.write(data)
            p.stdin_file = sf if i == 0 else p.stdin_file
        elif "name" in spec:
            p.collectors[i] = (spec["name"], int(spec.get("max") or (1 << 20)))
    p.collector_names = {n for (n, _) in p.collectors.values()}
    p.copy_out = list(cmd.get("copyOut") or [])
    p.copy_out_cached = list(cmd.get("copyOutCached") or [])
    p.cpu_ns = int(cmd.get("cpuLimit") or 0)
    clock = int(cmd.get("clockLimit") or 0)
    p.clock_ns = clock if clock else (2 * p.cpu_ns if p.cpu_ns else 300 * NS)
    return p


def spawn_cmd(p, cmd, extra_fd_map):
    """Start the process. extra_fd_map: {child_fd: os_fd} from pipeMapping."""
    readers = {}
    pass_fds = []
    stdin = subprocess.DEVNULL
    stdout = subprocess.DEVNULL
    stderr = subprocess.DEVNULL
    fd_assign = {}  # child fd -> parent fd to dup

    for i, (name, mx) in p.collectors.items():
        r, w = os.pipe()
        readers[i] = CollectorReader(r, mx)
        readers[i].start()
        fd_assign[i] = w
    for i, osfd in (extra_fd_map or {}).items():
        fd_assign[i] = osfd
    if p.stdin_file is not None:
        stdin = open(p.stdin_file, "rb")

    if 1 in fd_assign:
        stdout = fd_assign[1]
    if 2 in fd_assign:
        stderr = fd_assign[2]
    if 0 in fd_assign:
        stdin = fd_assign[0]
    for fd in fd_assign:
        if fd > 2:
            pass_fds.append(fd_assign[fd])  # not used by this judge, but safe

    mem = int(cmd.get("memoryLimit") or 0)
    stack = int(cmd.get("stackLimit") or 0)
    addr = bool(cmd.get("addressSpaceLimit"))
    try:
        proc = subprocess.Popen(
            p.argv,
            cwd=p.workdir,
            env=p.env,
            stdin=stdin,
            stdout=stdout,
            stderr=stderr,
            preexec_fn=_preexec(p.cpu_ns, mem, stack, addr, p.pin_cores),
            close_fds=True,
            pass_fds=tuple(pass_fds),
        )
        p.proc = proc
    except (OSError, ValueError) as e:
        p.proc = None
        p.err = str(e)
    finally:
        # parent must close its copies of the write ends / pipe fds
        for fd in set(fd_assign.values()):
            try:
                os.close(fd)
            except OSError:
                pass
        if hasattr(stdin, "close"):
            stdin.close()
    return readers


def wait_cmd(p, readers):
    """Wait with wall-clock enforcement; build the go-judge result dict."""
    if p.proc is None:
        return {"status": "File Error", "error": p.err or "exec failed",
                "exitStatus": -1, "time": 0, "runTime": 0, "memory": 0,
                "files": {}, "fileIds": {}}

    timer = threading.Timer(p.clock_ns / NS, _kill_group, args=(p,))
    timer.start()
    try:
        _, status, ru = os.wait4(p.proc.pid, 0)
    except ChildProcessError:
        status, ru = 0, None
    finally:
        timer.cancel()
    # keep Popen's bookkeeping consistent so its destructor doesn't re-wait
    p.proc.returncode = (os.waitstatus_to_exitcode(status)
                         if hasattr(os, "waitstatus_to_exitcode") else 0)

    for rd in readers.values():
        rd.join(timeout=5)

    cpu_ns = 0
    mem_bytes = 0
    if ru is not None:
        cpu_ns = int((ru.ru_utime + ru.ru_stime) * NS)
        mem_bytes = ru.ru_maxrss * 1024

    exited = os.WIFEXITED(status)
    exit_code = os.WEXITSTATUS(status) if exited else 0
    sig = os.WTERMSIG(status) if os.WIFSIGNALED(status) else 0

    overflow = any(rd.overflow for rd in readers.values())
    if p.wall_killed or sig == signal.SIGXCPU or (p.cpu_ns and cpu_ns > p.cpu_ns):
        st = "Time Limit Exceeded"
    elif overflow:
        st = "Output Limit Exceeded"
    elif sig:
        st = "Signalled"
    elif exit_code != 0:
        st = "Nonzero Exit Status"
    else:
        st = "Accepted"

    files = {}
    for i, (name, _mx) in p.collectors.items():
        files[name] = readers[i].data.decode("utf-8", errors="replace")
    for name in p.copy_out:
        if name in p.collector_names or name in files:
            continue  # compile calls list stdout/stderr redundantly -- no-op
        path = os.path.join(p.workdir, name)
        if os.path.isfile(path):
            with open(path, "rb") as f:
                files[name] = f.read().decode("utf-8", errors="replace")

    file_ids = {}
    missing_cached = None
    for name in p.copy_out_cached:
        path = os.path.join(p.workdir, name)
        if os.path.isfile(path):
            file_ids[name] = store_put(path)
        else:
            missing_cached = name
    if missing_cached and st == "Accepted":
        st = "File Error"

    res = {"status": st, "exitStatus": exit_code, "time": cpu_ns,
           "runTime": cpu_ns, "memory": mem_bytes, "files": files,
           "fileIds": file_ids}
    if sig:
        try:
            res["error"] = signal.Signals(sig).name
        except ValueError:
            res["error"] = "signal %d" % sig
    return res


def _kill_group(p):
    p.wall_killed = True
    try:
        os.killpg(os.getpgid(p.proc.pid), signal.SIGKILL)
    except (OSError, AttributeError):
        try:
            p.proc.kill()
        except OSError:
            pass


def handle_run(payload):
    cmds = payload.get("cmd") or []
    pipe_mapping = payload.get("pipeMapping") or []
    req_dir = os.path.join(STORE_DIR, "run_%s" % _new_id())
    prepared = []
    results = [None] * len(cmds)
    held_groups = []

    try:
        for idx, cmd in enumerate(cmds):
            wd = os.path.join(req_dir, str(idx))
            os.makedirs(wd, exist_ok=True)
            p = prepare_cmd(cmd, wd)
            if isinstance(p, dict):  # early File Error
                p.setdefault("exitStatus", -1)
                p.update(time=0, runTime=0, memory=0, files={}, fileIds={})
                results[idx] = p
                prepared.append(None)
            else:
                prepared.append(p)

        # build pipes for pipeMapping: {"in":{index,fd}} writes -> {"out":..} reads
        fd_maps = [dict() for _ in cmds]
        for m in pipe_mapping:
            r, w = os.pipe()
            win, wfd = m["in"]["index"], m["in"]["fd"]
            rin, rfd = m["out"]["index"], m["out"]["fd"]
            fd_maps[win][wfd] = w
            fd_maps[rin][rfd] = r

        # V2: atomically acquire one core group per live cmd, pin children.
        live = [p for p in prepared if p is not None]
        if CORE_POOL is not None and live:
            held_groups = CORE_POOL.acquire(len(live))
            for p, g in zip(live, held_groups):
                p.pin_cores = g

        all_readers = []
        for idx, p in enumerate(prepared):
            if p is None:
                all_readers.append({})
                continue
            all_readers.append(spawn_cmd(p, cmds[idx], fd_maps[idx]))

        # wait concurrently (interactive pairs must run simultaneously)
        threads = []
        for idx, p in enumerate(prepared):
            if p is None:
                continue

            def waiter(i=idx, pp=p):
                results[i] = wait_cmd(pp, all_readers[i])

            t = threading.Thread(target=waiter)
            t.start()
            threads.append(t)
        for t in threads:
            t.join()

        # Borderline-TLE retry (single-cmd runs only; see SHIM_TLE_RETRY above).
        if (SHIM_TLE_RETRY and len(cmds) == 1 and not pipe_mapping
                and results[0] is not None
                and results[0].get("status") == "Time Limit Exceeded"):
            cpu_limit = int(cmds[0].get("cpuLimit") or 0)
            used = int(results[0].get("time") or 0)
            if cpu_limit > 0 and used < SHIM_TLE_RETRY_FACTOR * cpu_limit:
                sys.stderr.write(
                    "[gojudge-shim] borderline TLE (cpu %.3fs / limit %.3fs "
                    "< x%.2f): retrying once\n"
                    % (used / NS, cpu_limit / NS, SHIM_TLE_RETRY_FACTOR))
                sys.stderr.flush()
                wd2 = os.path.join(req_dir, "retry0")
                os.makedirs(wd2, exist_ok=True)
                p2 = prepare_cmd(cmds[0], wd2)
                if not isinstance(p2, dict) and held_groups:
                    p2.pin_cores = held_groups[0]  # retry on the same core
                if isinstance(p2, dict):
                    sys.stderr.write("[gojudge-shim] retry prepare failed: %s\n"
                                     % p2.get("error"))
                    sys.stderr.flush()
                else:
                    readers2 = spawn_cmd(p2, cmds[0], {})
                    r2 = wait_cmd(p2, readers2)
                    if r2.get("status") != "Time Limit Exceeded":
                        # keep the retry; drop cached files of the discarded run
                        for fid in (results[0].get("fileIds") or {}).values():
                            store_del(fid)
                        sys.stderr.write(
                            "[gojudge-shim] retry kept: %s (cpu %.3fs)\n"
                            % (r2.get("status"), (r2.get("time") or 0) / NS))
                        results[0] = r2
                    else:
                        for fid in (r2.get("fileIds") or {}).values():
                            store_del(fid)
                        sys.stderr.write(
                            "[gojudge-shim] retry still TLE (cpu %.3fs); "
                            "keeping original result\n"
                            % ((r2.get("time") or 0) / NS))
                    sys.stderr.flush()
        return results
    finally:
        if held_groups and CORE_POOL is not None:
            CORE_POOL.release(held_groups)
        shutil.rmtree(req_dir, ignore_errors=True)


class Handler(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"

    def log_message(self, fmt, *args):  # quiet; errors still surface via stderr
        pass

    def _json(self, obj, code=200):
        body = json.dumps(obj).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        if self.path == "/version":
            self._json({"buildVersion": "gojudge-shim/1.1 (no-userns)",
                        "goVersion": "n/a", "platform": "linux",
                        "os": "linux", "copyOutOptional": True,
                        "pipeProxy": False,
                        # extra keys (ignored by the node judge): node speed
                        # class + retry policy, so eval logs are self-describing
                        "nodeSpeedCalibration": NODE_CALIB,
                        "tleRetry": SHIM_TLE_RETRY,
                        "tleRetryFactor": SHIM_TLE_RETRY_FACTOR,
                        "pinCores": SHIM_PIN_CORES or None,
                        "pinGroups": (len(CORE_POOL.groups)
                                      if CORE_POOL is not None else 0)})
            return
        m = re.match(r"^/file/([^/]+)$", self.path)
        if m:
            path = store_get(m.group(1))
            if path is None:
                self._json({"error": "not found"}, 404)
                return
            with open(path, "rb") as f:
                data = f.read()
            self.send_response(200)
            self.send_header("Content-Type", "application/octet-stream")
            self.send_header("Content-Length", str(len(data)))
            self.end_headers()
            self.wfile.write(data)
            return
        self._json({"error": "not found"}, 404)

    def do_POST(self):
        length = int(self.headers.get("Content-Length") or 0)
        body = self.rfile.read(length)
        if self.path == "/run":
            try:
                payload = json.loads(body)
            except json.JSONDecodeError as e:
                self._json({"error": "bad json: %s" % e}, 400)
                return
            try:
                self._json(handle_run(payload))
            except Exception as e:  # never hang the node judge
                self._json([{"status": "Internal Error", "error": str(e),
                             "exitStatus": -1, "time": 0, "runTime": 0,
                             "memory": 0, "files": {}, "fileIds": {}}
                            for _ in (payload.get("cmd") or [None])])
            return
        if self.path == "/file":
            ctype = self.headers.get("Content-Type") or ""
            m = re.search(r'boundary="?([^";]+)"?', ctype)
            if not m:
                self._json({"error": "no boundary"}, 400)
                return
            boundary = m.group(1).encode()
            # minimal multipart parse: first file part's payload
            parts = body.split(b"--" + boundary)
            data = None
            for part in parts:
                if b"\r\n\r\n" in part and b"filename=" in part.split(b"\r\n\r\n")[0]:
                    data = part.split(b"\r\n\r\n", 1)[1].rstrip(b"\r\n")
                    break
            if data is None:
                self._json({"error": "no file part"}, 400)
                return
            self._json(store_put_bytes(data))
            return
        self._json({"error": "not found"}, 404)

    def do_DELETE(self):
        m = re.match(r"^/file/([^/]+)$", self.path)
        if m and store_del(m.group(1)):
            self._json({})
        else:
            self._json({"error": "not found"}, 404)


def main():
    addr = "127.0.0.1:5050"
    store = None
    calibrate_only = False
    args = sys.argv[1:]
    i = 0
    while i < len(args):
        if args[i] == "-http-addr" and i + 1 < len(args):
            addr = args[i + 1]
            i += 2
        elif args[i] == "-dir" and i + 1 < len(args):
            store = args[i + 1]
            i += 2
        elif args[i] in ("-calibrate-only", "--calibrate-only"):
            calibrate_only = True
            i += 1
        elif args[i] in ("-parallelism", "-cgroup-prefix") and i + 1 < len(args):
            i += 2  # accepted for argv compatibility, ignored
        else:
            i += 1

    # Node speed calibration (measurement only; no limit scaling). Runs before
    # the server binds so the startup log always carries the speed class.
    NODE_CALIB.update(_calibrate_node_speed())
    print("[gojudge-shim] node speed: %.3e ops/s, factor %.3f vs ailab-EPYC "
          "ref %.3e (factor>1 = faster; MEASUREMENT only, limits unscaled)"
          % (NODE_CALIB["opsPerSec"], NODE_CALIB["speedFactor"],
             NODE_CALIB["refOpsPerSec"]), flush=True)
    if calibrate_only:
        print(json.dumps(NODE_CALIB, indent=2))
        return

    global STORE_DIR
    # abspath is load-bearing: workdirs derive from this and become Popen cwd,
    # so a relative -dir would make argv[0] resolve against the wrong base
    STORE_DIR = os.path.abspath(store or os.path.join(
        os.environ.get("TMPDIR", "/tmp"), "gojudge-shim-%d" % os.getpid()))
    os.makedirs(STORE_DIR, exist_ok=True)

    host, port = addr.rsplit(":", 1)
    srv = ThreadingHTTPServer((host, int(port)), Handler)
    print("[gojudge-shim] listening on %s, store=%s (NO userns; rlimit "
          "semantics matching go-judge's cgroup-less fallback; "
          "borderline-TLE retry=%s x%.2f)"
          % (addr, STORE_DIR, "on" if SHIM_TLE_RETRY else "off",
             SHIM_TLE_RETRY_FACTOR),
          flush=True)
    if CORE_POOL is not None:
        print("[gojudge-shim-v2] core pinning ON: pool=%s (%d groups x %d "
              "core(s)); shim affinity=%s"
              % (SHIM_PIN_CORES, len(CORE_POOL.groups), SHIM_CORES_PER_RUN,
                 sorted(os.sched_getaffinity(0))), flush=True)
    else:
        print("[gojudge-shim-v2] core pinning OFF (SHIM_PIN_CORES unset)",
              flush=True)
    try:
        srv.serve_forever()
    finally:
        shutil.rmtree(STORE_DIR, ignore_errors=True)


if __name__ == "__main__":
    main()
