#!/usr/bin/env python3
"""Build the MLS-Bench *training* root (task variants for agentic RL).

Why a separate root
-------------------
`mlsbench` resolves every task as ``PROJECT_ROOT / "tasks" / <task_name>`` where
``PROJECT_ROOT = Path(mlsbench/__init__.py).resolve().parent.parent.parent``.
There is no tasks-dir override env var, and ``.resolve()`` follows symlinks — so
a training task can only live in a root whose ``src/mlsbench`` is a REAL copy.
We therefore materialise a third checkout:

    MLS-Bench-train/
      src/      real copy of MLS-Bench-dev/src        (1.9 MB, rsync'd)
      vendor -> symlink to MLS-Bench-dev/vendor       (110 GB: images/data, read-only use)
      holdout/  per-task symlinks into MLS-Bench-dev/holdout
                (task parser.py / mid_edit.py hardcode holdout/<ORIGINAL task name>)
      tasks/    ONLY the training variants (<orig>_tv1) — never the eval task names
      logs/     real dir (agent run logs)

Neither MLS-Bench-dev (eval root) nor MLS-Bench (main root) is modified.

Variant construction (per base task)
------------------------------------
  * copy tasks/<base> -> tasks/<base>_tv1 (minus __pycache__)
  * leaderboard.csv is filtered to header + ``baseline:*`` rows  => the SAME
    anchors as the eval task (BaselineAnchors only reads baseline rows), with no
    eval agent history carried over and no shared file with the eval task.
  * task_description.md: the ``## Research Question`` section is replaced by the
    overlay's re-aimed question; every other section (background, implementation
    contract, evaluation) is kept verbatim because the environment and the
    scoring contract are unchanged.
  * edits/custom_template.py: the config.json editable window [start, end] is
    spliced out and replaced with the overlay's ``editable.py``. The FIXED head
    (lines < start) and FIXED tail (lines > end) are preserved byte-for-byte, so
    the harness/parser contract cannot drift. config.json's edit ``end`` is
    recomputed as start + len(new_block) - 1.

Overlays live in FrontierSmith/training_tasks/mlsbench_tv1/<base>_tv1/
    research_question.md   -> body of the new "## Research Question" section
    editable.py            -> new editable block (replaces lines [start, end])

Usage:
  python scripts/mlsbench_build_train_tasks.py                 # all overlays
  python scripts/mlsbench_build_train_tasks.py --tasks ml-clustering-algorithm
  python scripts/mlsbench_build_train_tasks.py --sync-src      # re-rsync src/ only
"""
from __future__ import annotations

import argparse
import csv
import json
import shutil
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OVERLAY_ROOT = PROJECT_ROOT / "training_tasks" / "mlsbench_tv1"
DEV_ROOT = Path("/scratch/gpfs/CHIJ/bohan/MLS-Bench-dev")
TRAIN_ROOT = Path("/scratch/gpfs/CHIJ/bohan/MLS-Bench-train")
SUFFIX = "_tv1"  # default; override with --suffix _tv2 .. _tv5 (overlay root must match)


def log(msg: str) -> None:
    print(f"[build-train-tasks] {msg}", flush=True)


# ---------------------------------------------------------------------------
# root skeleton
# ---------------------------------------------------------------------------

def ensure_root(dev_root: Path, train_root: Path, sync_src: bool = True) -> None:
    train_root.mkdir(parents=True, exist_ok=True)
    (train_root / "tasks").mkdir(exist_ok=True)
    (train_root / "logs").mkdir(exist_ok=True)

    if sync_src:
        subprocess.run(
            ["rsync", "-a", "--delete", "--exclude", "__pycache__",
             f"{dev_root}/src/", f"{train_root}/src/"],
            check=True,
        )
        log(f"src/ synced from {dev_root}/src")

    vendor = train_root / "vendor"
    if not vendor.exists():
        vendor.symlink_to(dev_root / "vendor")
        log("vendor -> dev vendor (symlink)")

    holdout = train_root / "holdout"
    holdout.mkdir(exist_ok=True)
    n = 0
    for src in sorted((dev_root / "holdout").iterdir()):
        dst = holdout / src.name
        if not dst.exists():
            dst.symlink_to(src)
            n += 1
    if n:
        log(f"holdout/: {n} new symlinks into dev holdout")

    # marker so nobody mistakes this for an eval checkout
    marker = train_root / "TRAINING_ROOT.md"
    if not marker.exists():
        marker.write_text(
            "# MLS-Bench TRAINING root\n\n"
            "Generated by FrontierSmith/scripts/mlsbench_build_train_tasks.py.\n"
            "Contains ONLY agentic-RL training task variants (`*_tv1`). It shares\n"
            "vendor/ and holdout/ with MLS-Bench-dev by symlink and carries its own\n"
            "copy of src/. Do NOT run eval from here; eval root is MLS-Bench-dev.\n"
        )


# ---------------------------------------------------------------------------
# per-task variant
# ---------------------------------------------------------------------------

def filter_leaderboard(src: Path, dst: Path) -> int:
    """Copy header + baseline:* rows only (anchors identical, history dropped)."""
    with src.open(newline="") as f:
        reader = csv.DictReader(f)
        fields = reader.fieldnames or []
        rows = [r for r in reader if str(r.get("model", "")).startswith("baseline:")]
    with dst.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for r in rows:
            w.writerow(r)
    return len(rows)


def replace_research_question(md: str, new_body: str) -> str:
    """Swap the body of the '## Research Question' section, keep every other section."""
    lines = md.split("\n")
    start = None
    for i, ln in enumerate(lines):
        if ln.strip().lower().startswith("## research question"):
            start = i
            break
    if start is None:
        # no RQ heading: prepend one
        return f"## Research Question\n{new_body.strip()}\n\n" + md
    end = len(lines)
    for j in range(start + 1, len(lines)):
        if lines[j].startswith("## "):
            end = j
            break
    head = lines[:start + 1]
    tail = lines[end:]
    return "\n".join(head + ["", new_body.strip(), ""] + tail)


def splice_template(template: str, start: int, end: int, new_block: str) -> tuple[str, int]:
    """Replace 1-indexed lines [start, end] with *new_block*; return (text, new_end)."""
    lines = template.split("\n")
    if start < 1 or end > len(lines) or start > end:
        raise ValueError(f"bad edit window [{start},{end}] for {len(lines)}-line template")
    block = new_block.rstrip("\n").split("\n")
    out = lines[:start - 1] + block + lines[end:]
    return "\n".join(out), start + len(block) - 1


def build_task(base: str, dev_root: Path, train_root: Path, overlay_root: Path,
               suffix: str = SUFFIX) -> dict:
    name = base + suffix
    src_dir = dev_root / "tasks" / base
    dst_dir = train_root / "tasks" / name
    ov_dir = overlay_root / name
    rec = {"task": name, "base": base}

    if not src_dir.is_dir():
        raise FileNotFoundError(src_dir)
    if not (ov_dir / "research_question.md").exists() or not (ov_dir / "editable.py").exists():
        raise FileNotFoundError(f"overlay incomplete: {ov_dir}")

    if dst_dir.exists():
        shutil.rmtree(dst_dir)
    shutil.copytree(src_dir, dst_dir, ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))

    # 1. anchors: baseline rows only
    lb = dst_dir / "leaderboard.csv"
    if lb.exists():
        rec["baseline_rows"] = filter_leaderboard(src_dir / "leaderboard.csv", lb)

    # 2. research question
    md_path = dst_dir / "task_description.md"
    md = md_path.read_text()
    new_md = replace_research_question(md, (ov_dir / "research_question.md").read_text())
    md_path.write_text(new_md)

    # 3. scaffold splice + config edit-window update
    cfg_path = dst_dir / "config.json"
    cfg = json.loads(cfg_path.read_text())
    f0 = None
    for entry in cfg.get("files", []):
        if entry.get("edit"):
            f0 = entry
            break
    if f0 is None:
        raise ValueError(f"{base}: no editable file entry in config.json")
    win = f0["edit"][0]
    tmpl_path = dst_dir / "edits" / "custom_template.py"
    text, new_end = splice_template(
        tmpl_path.read_text(), int(win["start"]), int(win["end"]),
        (ov_dir / "editable.py").read_text(),
    )
    tmpl_path.write_text(text)
    rec["edit_window"] = [int(win["start"]), int(win["end"]), new_end]
    win["end"] = new_end
    cfg_path.write_text(json.dumps(cfg, indent=2) + "\n")

    # 4. compile check on the spliced scaffold
    import tempfile
    import py_compile
    try:
        with tempfile.NamedTemporaryFile(suffix=".pyc") as tf:
            py_compile.compile(str(tmpl_path), doraise=True, cfile=tf.name)
        rec["compiles"] = True
    except Exception as e:  # noqa: BLE001
        rec["compiles"] = False
        rec["compile_error"] = str(e)
    return rec


def build_task_as_is(base: str, dev_root: Path, train_root: Path, suffix: str = "_train") -> dict:
    """Import an existing task into the training root unchanged (new name, own leaderboard).

    Used for tasks that are already outside the eval set: the research question and
    scaffold are kept, only the identity is separated so RL never writes into the
    eval checkout.
    """
    name = base + suffix
    src_dir = dev_root / "tasks" / base
    dst_dir = train_root / "tasks" / name
    if not src_dir.is_dir():
        raise FileNotFoundError(src_dir)
    if dst_dir.exists():
        shutil.rmtree(dst_dir)
    shutil.copytree(src_dir, dst_dir, ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
    rec = {"task": name, "base": base, "mode": "as_is"}
    lb = dst_dir / "leaderboard.csv"
    if lb.exists():
        rec["baseline_rows"] = filter_leaderboard(src_dir / "leaderboard.csv", lb)
    return rec


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tasks", nargs="*", default=None,
                    help="base task names (default: every overlay present)")
    ap.add_argument("--as-is", nargs="*", default=None,
                    help="import these tasks unchanged as <name>_train (no overlay needed)")
    ap.add_argument("--dev-root", default=str(DEV_ROOT))
    ap.add_argument("--train-root", default=str(TRAIN_ROOT))
    ap.add_argument("--overlay-root", default=str(OVERLAY_ROOT))
    ap.add_argument("--suffix", default=SUFFIX,
                    help="variant suffix, e.g. _tv2 (overlay dirs must be <base><suffix>)")
    ap.add_argument("--sync-src", action="store_true", help="only refresh the root skeleton")
    ap.add_argument("--skip-skeleton", action="store_true",
                    help="assume src/vendor/holdout are already in place (safe for parallel builds)")
    args = ap.parse_args()

    dev_root, train_root = Path(args.dev_root), Path(args.train_root)
    overlay_root = Path(args.overlay_root)
    if not args.skip_skeleton:
        ensure_root(dev_root, train_root)
    if args.sync_src:
        return 0

    if args.as_is:
        for b in args.as_is:
            rec = build_task_as_is(b, dev_root, train_root)
            log(f"{rec['task']}: imported as-is, baselines={rec.get('baseline_rows')}")
        if not args.tasks:
            return 0

    suffix = args.suffix
    if args.tasks:
        bases = list(args.tasks)
    else:
        bases = sorted(
            d.name[: -len(suffix)] for d in overlay_root.iterdir()
            if d.is_dir() and d.name.endswith(suffix)
        )
    if not bases:
        log("no overlays found — nothing to build")
        return 1

    ok, fail = [], []
    for b in bases:
        try:
            rec = build_task(b, dev_root, train_root, overlay_root, suffix=suffix)
            (ok if rec.get("compiles") else fail).append(rec)
            log(f"{rec['task']}: window {rec['edit_window'][0]}-{rec['edit_window'][1]} "
                f"-> {rec['edit_window'][0]}-{rec['edit_window'][2]}, "
                f"baselines={rec.get('baseline_rows')}, compiles={rec.get('compiles')}")
        except Exception as e:  # noqa: BLE001
            fail.append({"task": b + suffix, "error": repr(e)})
            log(f"{b}{suffix}: FAILED {e!r}")
    log(f"built {len(ok)} ok, {len(fail)} failed -> {train_root}/tasks")
    return 0 if not fail else 2


if __name__ == "__main__":
    sys.exit(main())
