# TIER: strong
# THE INSIGHT: the t exponents are told to form an arithmetic progression
# e_i = a + i*d (secret a, d; 1<=d<=d_max, d_max public). Substituting the query
# depth x=g^k, the roots of the underlying order-t recurrence are
# z_i = g^{e_i} = g^a * (g^d)^i -- a GEOMETRIC family generated by just TWO
# scalars (g^a, g^d) instead of t independent unknowns. So instead of the
# generic Ben-Or-Tiwari/Prony recipe (fit an order-t recurrence from 2t samples,
# which is information-theoretically required when the roots are unconstrained),
# we do a small 2-D search over (a, d): for each hypothesis, the t candidate
# roots z_i are FULLY DETERMINED, so the t coefficients c_i solve a plain t x t
# linear (Vandermonde) system using only t of the Q samples -- and the handful
# of LEFTOVER samples (Q - t of them, not used to fit anything) are enough to
# VERIFY/reject the hypothesis outright. This is why Q ~ t + O(1) queries
# suffice here, well below the 2t a structure-unaware solver would need.
import sys, json


def gauss_solve(A, b, p, n):
    A = [row[:] for row in A]
    b = b[:]
    for col in range(n):
        piv = None
        for r in range(col, n):
            if A[r][col] % p != 0:
                piv = r; break
        if piv is None:
            return None
        A[col], A[piv] = A[piv], A[col]
        b[col], b[piv] = b[piv], b[col]
        inv = pow(A[col][col], p - 2, p)
        A[col] = [(x * inv) % p for x in A[col]]
        b[col] = (b[col] * inv) % p
        for r in range(n):
            if r != col and A[r][col] % p != 0:
                factor = A[r][col] % p
                A[r] = [(A[r][j] - factor * A[col][j]) % p for j in range(n)]
                b[r] = (b[r] - factor * b[col]) % p
    return [x % p for x in b]


inst = json.load(sys.stdin)
p = inst["p"]; g = inst["g"]; t = inst["t"]; d_max = inst["d_max"]
Q = inst["Q"]; s = inst["s"]

terms = []
for d in range(1, d_max + 1):
    maxa = p - 2 - (t - 1) * d
    if maxa < 0:
        continue
    gd = pow(g, d, p)
    gd_pows = [pow(gd, i, p) for i in range(t)]
    found = False
    for a in range(0, maxa + 1):
        ga = pow(g, a, p)
        zs = [(ga * gd_pows[i]) % p for i in range(t)]
        M = [[pow(zs[i], k, p) for i in range(t)] for k in range(t)]
        rhs = [s[k] % p for k in range(t)]
        sol = gauss_solve(M, rhs, p, t)
        if sol is None:
            continue
        ok = True
        for k in range(t, Q):
            pred = sum(sol[i] * pow(zs[i], k, p) for i in range(t)) % p
            if pred != s[k] % p:
                ok = False; break
        if ok:
            terms = [[a + i * d, sol[i]] for i in range(t)]
            found = True
            break
    if found:
        break

print(json.dumps({"terms": terms}))
